//! Real plugin implementation for Action1 (cloud-hosted, patch-management-
//! focused RMM, <https://www.action1.com>), see `docs/PLUGIN_ARCHITECTURE.md`
//! section "Action1-Plugin". Structurally closest to `plugin::intune`: OAuth2
//! client-credentials style authentication against a token endpoint, no
//! per-method-call token caching (fetched fresh per public method call,
//! exactly the same "simple, correct enough for v1" tradeoff `plugin::ninja`/
//! `plugin::intune` already document). Like `plugin::ninja`/
//! `plugin::tacticalrmm`, a connection is NOT bound to exactly one local
//! customer -- one Action1 account manages multiple "Organizations", each
//! mapped independently (`Action1OrgMapping`/`Config::action1_org_mappings`,
//! maintained by `commands::action1`).
//!
//! Every fact below is researched against Action1's own official prose docs
//! and its live OpenAPI 3.1/Swagger spec, not guessed:
//!
//! - **Authentication -- a documented, UNRESOLVED disagreement between
//!   Action1's own sources, deliberately preserved here rather than silently
//!   picked**: `POST {base_url}/oauth2/token`. Action1's prose documentation
//!   shows `Content-Type: application/x-www-form-urlencoded` with body
//!   `client_id=...&client_secret=...`; its own interactive Swagger/OpenAPI
//!   3.1 spec instead shows `Content-Type: application/json` with body
//!   `{"client_id": "...", "client_secret": "..."}`. Neither source shows a
//!   `grant_type` field anywhere -- unlike `plugin::ninja`/`plugin::intune`'s
//!   verified `grant_type=client_credentials`. **This module implements the
//!   JSON variant** (`fetch_access_token`/`TokenRequest` below): a JSON body,
//!   `Content-Type: application/json` (`ureq`'s `send_json`), no `grant_type`
//!   field at all. Ruling, per the brief that commissioned this integration:
//!   the interactive Swagger spec is more likely to reflect the live
//!   server's actual accepted contract than static prose describing it.
//!   **This is genuinely unverified against a live Action1 call** -- if a
//!   real account later proves the form-urlencoded prose variant correct
//!   instead, `fetch_access_token`/`TokenRequest` is the one place to change,
//!   and `token_request_body_is_json_with_client_id_and_client_secret_only`
//!   below pins the current (JSON) shape so that fix shows up as a one-line
//!   diff, not a rediscovery. Response (both sources agree on this):
//!   `{"access_token": "<JWT>", "refresh_token": "...", "expires_in": 3600,
//!   "token_type": "bearer"}`, used as `Authorization: Bearer <access_token>`
//!   on every subsequent call. The Client ID/Secret pair is generated by the
//!   user in the Action1 console (Configuration -> Users and API
//!   Credentials); the Role assigned there controls the credential's access
//!   scope -- there is no separate `scope` request parameter to send (unlike
//!   `plugin::ninja`'s `scope=monitoring`/`plugin::intune`'s
//!   `scope=https://graph.microsoft.com/.default`).
//! - **Base URL -- four fixed regional hosts, each already including
//!   `/api/3.0`**: `https://app.action1.com/api/3.0` (North America),
//!   `https://app.na-2.action1.com/api/3.0` (North America 2),
//!   `https://app.eu.action1.com/api/3.0` (Europe), and
//!   `https://app.au.action1.com/api/3.0` (Australia). Like NinjaOne/
//!   Snipe-IT/Tactical RMM (and unlike Level.io/Intune's fixed hosts), the
//!   user supplies this on `Action1ConnectionMeta.base_url` -- the frontend
//!   offers the four options as a `<select>` (see
//!   `Action1PluginSection.tsx`), but the field itself stays plain
//!   `String`, so a fifth region Action1 might add later needs no Rust
//!   change, only a frontend option list update.
//! - **Organizations (multi-tenancy)**: `GET {base_url}/organizations`,
//!   wrapped in Action1's generic `ResultPage` envelope (used across the
//!   whole API, see `parse_result_page` below):
//!   `{"id","type":"ResultPage","name","self","items":[{"id","type":
//!   "Organization","name","description","self","access"}],"total_items",
//!   "limit","next_page","prev_page"}`. An organization's own `id` field
//!   shape wasn't confirmed beyond a placeholder `"1"` in the docs -- treated
//!   as an opaque value (string OR number tolerated, mirroring
//!   `plugin::ninja::map_organization`'s defensive handling of the same
//!   uncertainty), not assumed numeric.
//! - **Endpoints (devices)**: `GET {base_url}/endpoints/managed/{orgId}`,
//!   same `ResultPage` envelope -- IMPORTANT, this is a PER-ORGANIZATION
//!   endpoint, unlike NinjaOne's `/v2/devices` (which lists every device of
//!   the whole tenant in one call regardless of organization). There is no
//!   documented "all endpoints across the account" call -- fetching a
//!   connection's full device list genuinely requires one
//!   `/endpoints/managed/{orgId}` walk per organization (see
//!   `list_organizations_with_endpoints` below), which is exactly why the
//!   rate-limit note further down matters here more than for NinjaOne/
//!   Tactical RMM. Verified per-endpoint fields used here: `id` (used as
//!   `Action1Endpoint::external_id`), `device_name` (the real hostname),
//!   `name` (a separate, user-editable display label -- `device_name` is
//!   preferred for `Action1Endpoint::name`, falling back to `name` and then
//!   to `id`, matching how every other plugin here prefers a real hostname
//!   over a free-text label), `address` (IP), `platform`, `status` (enum
//!   `Connected`/`Disconnected`/`Pending Uninstall` -- the real connectivity
//!   field, passed straight through as a free string, no Rust enum, same
//!   "future value won't break parsing" convention as
//!   `plugin::tacticalrmm::TacticalRmmAgent::status`), and, critically,
//!   **`organization_id`** -- a genuine UUID-string foreign key directly on
//!   the endpoint object. Unlike Tactical RMM (whose agent list carries only
//!   a `client_name` STRING, forcing a name-based join, see
//!   `plugin::tacticalrmm` module docs), Action1 endpoints can be grouped by
//!   organization via a real ID join -- `commands::action1::
//!   group_endpoints_by_organization` is written around that verified fact,
//!   not copied blindly from Tactical RMM's name-join workaround.
//!   `MAC`/`OS`/`architecture`/`last_seen`/`agent_version` are real,
//!   documented fields on the same object but are NOT mapped into
//!   `Action1Endpoint` -- this module only maps what it actually uses, the
//!   same "only map what's used" convention `plugin::intune` already
//!   documents for Graph's much larger `managedDevices` object.
//! - **`online_status` is NOT connectivity -- do not confuse with
//!   `status`**: `online_status` is a separate enum
//!   (`SUCCESS`/`WARNING`/`ERROR`), a HEALTH flag (roughly: "is monitoring
//!   currently reporting cleanly"), not "is this endpoint online". It is
//!   deliberately never read anywhere in this module -- `status` (the
//!   `Connected`/`Disconnected`/`Pending Uninstall` enum) is the one and only
//!   field this integration surfaces as the device's connectivity state.
//! - **Pagination**: query params `limit` (page size) and `from` (offset of
//!   the first record) on the initial request; `next_page`/`prev_page` in
//!   the `ResultPage` envelope are pre-built RELATIVE URLs that already
//!   contain the next `from`/`limit` (Action1's own docs example:
//!   `/API/endpoints/managed?from=60&limit=10`) -- so continuing a walk never
//!   needs this module to compute `from`/`limit` itself, only to follow
//!   `next_page` (see `fetch_all_pages`/`origin_of` below). The docs don't
//!   explicitly confirm null-vs-absent-vs-empty-string behaviour on the last
//!   page, so an empty string is treated the same as a genuinely absent
//!   field -- "no more pages" -- defensively, instead of risking an infinite
//!   loop on a value that's present but empty. `MAX_PAGES` caps the walk
//!   regardless, the same defensive convention as `plugin::intune::MAX_PAGES`/
//!   `plugin::level::MAX_PAGES`.
//! - **Single device detail**: `GET {base_url}/endpoints/managed/{orgId}/
//!   {endpointId}` (also given directly by the `self` field on each list
//!   item) -- raw JSON pass-through, like every other plugin's
//!   `get_system_details`. IMPORTANT interface note: this call genuinely
//!   needs BOTH the organization id and the endpoint id in the URL path,
//!   unlike Tactical RMM's `/agents/{agent_id}/` (a single ID is enough
//!   there). The generic `Plugin` trait's `get_system_details`/`link_system`
//!   only carry a single `external_id` string -- so the REAL, recommended
//!   path for a single-device detail lookup is the inherent method
//!   `get_endpoint_details(credentials, organization_id, endpoint_id)`
//!   below, called directly by `commands::action1` (which always has
//!   `organization_id` in scope from the org/device grouping it already
//!   holds). The trait method `get_system_details` still exists, for
//!   interface conformance and any future generic caller, implemented via a
//!   documented `"<organization_id>:<endpoint_id>"` compound-string encoding
//!   of `external_id` (see `split_compound_external_id`) -- `commands::
//!   action1` itself never relies on that encoding, it always calls
//!   `get_endpoint_details` directly with the two IDs it already has.
//! - **Rate limit -- noticeably tighter than this codebase's other RMM
//!   plugins**: Action1 recommends staying under 30 requests/minute per
//!   Enterprise account, counted across ALL endpoints of the API (compare
//!   Tactical RMM: no documented limit; NinjaOne: no documented limit in
//!   this codebase's other module docs; the brief that commissioned this
//!   integration separately notes Datto RMM at 600/60s and Pulseway at
//!   roughly 3600/hour as other reference points). Exceeding it returns
//!   `429` with `{"status":429,"details":{"retry_after":<seconds>}}`. This
//!   matters concretely here because, per the per-organization endpoint
//!   listing above, `sync_action1_connection` (see `commands::action1`)
//!   already needs roughly `1 + (1 organizations call) + (1 endpoints call
//!   per organization)` requests for a routine sync BEFORE counting
//!   pagination or already-linked-device detail refreshes -- for an account
//!   with many organizations that adds up fast against a 30/minute budget.
//!   The existing "full fetch per sync, triggered manually" pattern (see
//!   `plugin::tacticalrmm`/`plugin::ninja`) is left as-is here too -- it's
//!   fine for the realistic single-admin fleet sizes this app targets -- but
//!   this limit is called out explicitly so a future change doesn't add
//!   still more per-sync calls (e.g. a live per-device detail refresh for
//!   every listed device, not just already-linked ones) without someone
//!   noticing the budget it eats into. `list_organizations_with_endpoints`
//!   below already fetches its OAuth2 token exactly ONCE per sync (not once
//!   per organization) specifically to keep that per-sync request count as
//!   low as the per-organization endpoint listing allows.
//! - **Web dashboard deep-link**: not documented anywhere reachable --
//!   deliberately left out, the same honest-omission principle as
//!   `plugin::tacticalrmm`'s missing `tacticalrmm_url`/`plugin::snipeit`'s
//!   always-`None` `hostname`/`ip_address` (see their own module docs).
//! - **HTTP client**: `ureq`, synchronous, the same dependency every other
//!   plugin module here already uses -- no new Cargo dependency needed.
//! - **Credential encoding**: Action1 needs two secret values (`client_id`,
//!   `client_secret`) -- `PluginCredentials.secret` is, per the trait
//!   contract, a single opaque string the plugin interprets itself, encoded
//!   here as JSON (`serde_json::to_string`/`from_str`), the exact same
//!   two-value pattern `plugin::ninja::NinjaCredentials` already uses.

use std::time::Duration;

use serde::{Deserialize, Serialize};
use ureq::Agent;

use super::{ExternalSystem, Plugin, PluginCredentials, PluginError};

/// Protection against a misbehaving remote end (a `next_page` that never
/// stops appearing): more than `MAX_PAGES` pages of a single `ResultPage`
/// walk are never fetched, the same defensive convention as
/// `plugin::intune::MAX_PAGES`/`plugin::level::MAX_PAGES`.
const MAX_PAGES: usize = 50;

/// Non-secret metadata of an Action1 connection, as stored in `config.toml`
/// (`Config::action1_connections`). The client ID/secret pair belongs, per
/// the credential principle, exclusively in the OS keyring, never here.
/// Deliberately WITHOUT `customer_id` -- a connection is an Action1 account,
/// not a local customer; which Action1 "Organization" within this account
/// corresponds to which local customer is tracked granularly in
/// `Action1OrgMapping`/`Config::action1_org_mappings`, exactly the same
/// principle as `plugin::ninja::NinjaConnectionMeta`/
/// `plugin::tacticalrmm::TacticalRmmConnectionMeta`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Action1ConnectionMeta {
    pub id: String,
    pub label: String,
    pub base_url: String,
}

/// Mapping of a single Action1 "Organization" (within a connection) to a
/// local customer. Lives in `Config::action1_org_mappings`, not in
/// `Action1ConnectionMeta` -- a connection can see multiple organizations,
/// each mapped (or left unmapped) independently, analogous to
/// `plugin::ninja::NinjaOrgMapping`/`plugin::tacticalrmm::
/// TacticalRmmClientMapping`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Action1OrgMapping {
    pub connection_id: String,
    pub organization_id: String,
    pub organization_name: String,
    pub customer_id: i64,
}

/// An organization reported by `GET /organizations`. Separate from
/// `ExternalSystem` (those are endpoints/devices) -- its own, small shape
/// type, analogous to `plugin::ninja::NinjaOrganization`/
/// `plugin::tacticalrmm::TacticalRmmClient`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Action1Organization {
    pub id: String,
    pub name: String,
}

/// A single endpoint (device) from `GET /endpoints/managed/{orgId}`,
/// enriched with organization membership (`organization_id`, a genuine
/// verified foreign key, see module docs) -- needed by
/// `commands::action1::sync_action1_connection` for grouping by organization
/// and for display, which the generic, plugin-agnostic `ExternalSystem` type
/// from `plugin::mod` deliberately does not provide.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Action1Endpoint {
    pub external_id: String,
    pub name: String,
    pub ip_address: Option<String>,
    /// One of `"Connected"`/`"Disconnected"`/`"Pending Uninstall"` per
    /// Action1's own verified `status` enum -- kept as a free-form string,
    /// not a Rust enum, so a future additional value doesn't break parsing
    /// (see module docs). This is connectivity -- NOT the same thing as
    /// Action1's separate `online_status` health flag, which this module
    /// deliberately never reads (see module docs).
    pub status: Option<String>,
    pub platform: Option<String>,
    pub organization_id: String,
    /// Never populated from the raw endpoint JSON itself -- Action1's
    /// `/endpoints/managed/{orgId}` response has no organization NAME field
    /// on the endpoint object, only `organization_id`. Filled in by
    /// `map_endpoint`/`map_endpoints_response` from the organization name
    /// the caller already knows (see `list_endpoints`/
    /// `list_organizations_with_endpoints` below, both of which fetch the
    /// organization list before fetching any endpoints and can pass its name
    /// straight through) -- so a live call always has this populated, while
    /// a hand-built `Action1Endpoint` in a unit test may leave it `None`.
    pub organization_name: Option<String>,
}

/// The two secret values an Action1 connection needs to authenticate.
/// `PluginCredentials.secret` is, per the trait contract, a single opaque
/// string that the plugin interprets itself -- here encoded as JSON
/// (`serde_json::to_string`/`from_str`), analogous to
/// `plugin::ninja::NinjaCredentials`.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Action1Credentials {
    pub client_id: String,
    pub client_secret: String,
}

/// The OAuth2 token request body -- see module docs on the documented,
/// unresolved disagreement between Action1's prose docs (form-urlencoded)
/// and its Swagger spec (JSON, implemented here) for this exact shape.
/// Deliberately just these two fields -- no `grant_type`, confirmed absent
/// from BOTH of Action1's own conflicting sources.
#[derive(Debug, Clone, Serialize)]
struct TokenRequest<'a> {
    client_id: &'a str,
    client_secret: &'a str,
}

#[derive(Debug, Deserialize)]
struct TokenResponse {
    access_token: String,
}

/// A plugin object for exactly one configured Action1 connection. `id` here
/// is already the fully qualified identifier (`"action1:<connection_id>"`),
/// so that `Plugin::id()` works unmodified as the `plugin_id`/keyring
/// account (see trait documentation in `plugin::mod`).
pub struct Action1Plugin {
    id: String,
    base_url: String,
}

impl Action1Plugin {
    pub fn new(id: String, base_url: String) -> Self {
        Self { id, base_url }
    }

    /// Live fetch of this connection's organization list
    /// (`GET /organizations`, one full `ResultPage` walk). Separate from the
    /// `Plugin` trait method `list_systems`, because organizations are not
    /// endpoints and the generic trait has no room for that -- analogous to
    /// `plugin::ninja::NinjaPlugin::list_organizations`/
    /// `plugin::tacticalrmm::TacticalRmmPlugin::list_clients`. Fetches its
    /// own OAuth2 token, independent of any other call -- for the combined,
    /// single-token organizations+endpoints walk `sync_action1_connection`
    /// actually uses, see `list_organizations_with_endpoints` instead (see
    /// its own docs and the module-level rate-limit note on why that
    /// distinction matters for Action1 specifically).
    pub fn list_organizations(
        &self,
        credentials: &PluginCredentials,
    ) -> Result<Vec<Action1Organization>, PluginError> {
        let creds = parse_credentials(credentials)?;
        let agent = build_agent();
        let token = fetch_access_token(&agent, &self.base_url, &creds)?;
        let raw = fetch_all_pages(&agent, &self.base_url, "/organizations", &token)?;
        map_organizations_response(&raw)
    }

    /// Live fetch of one organization's endpoint list
    /// (`GET /endpoints/managed/{organization_id}`, one full `ResultPage`
    /// walk). `organization_name` is threaded through purely for display
    /// (see `Action1Endpoint::organization_name` docs) -- pass `None` if it
    /// isn't already known; the endpoint's own verified `organization_id`
    /// field is always populated regardless. Fetches its own OAuth2 token --
    /// for fetching every organization's endpoints in one sync with a SINGLE
    /// token fetch, see `list_organizations_with_endpoints`.
    pub fn list_endpoints(
        &self,
        credentials: &PluginCredentials,
        organization_id: &str,
        organization_name: Option<&str>,
    ) -> Result<Vec<Action1Endpoint>, PluginError> {
        let creds = parse_credentials(credentials)?;
        let agent = build_agent();
        let token = fetch_access_token(&agent, &self.base_url, &creds)?;
        let raw = fetch_all_pages(
            &agent,
            &self.base_url,
            &format!("/endpoints/managed/{organization_id}"),
            &token,
        )?;
        Ok(map_endpoints_response(&raw, organization_name))
    }

    /// The combined call `commands::action1::sync_action1_connection`
    /// actually uses: fetches the OAuth2 token exactly ONCE, then the
    /// organization list, then walks EVERY organization's endpoint list with
    /// that same token -- deliberately not `list_organizations` followed by
    /// N separate `list_endpoints` calls (each of which would re-authenticate
    /// on its own). See the module-level rate-limit note: Action1's
    /// per-organization endpoint listing already costs one request per
    /// organization on top of the organization list itself, so this method
    /// exists specifically to not multiply that further with N redundant
    /// token round-trips.
    pub fn list_organizations_with_endpoints(
        &self,
        credentials: &PluginCredentials,
    ) -> Result<(Vec<Action1Organization>, Vec<Action1Endpoint>), PluginError> {
        let creds = parse_credentials(credentials)?;
        let agent = build_agent();
        let token = fetch_access_token(&agent, &self.base_url, &creds)?;
        let orgs_raw = fetch_all_pages(&agent, &self.base_url, "/organizations", &token)?;
        let organizations = map_organizations_response(&orgs_raw)?;

        let mut endpoints = Vec::new();
        for org in &organizations {
            let raw = fetch_all_pages(
                &agent,
                &self.base_url,
                &format!("/endpoints/managed/{}", org.id),
                &token,
            )?;
            endpoints.extend(map_endpoints_response(&raw, Some(org.name.as_str())));
        }
        Ok((organizations, endpoints))
    }

    /// Live fetch of exactly one endpoint's detail
    /// (`GET /endpoints/managed/{organization_id}/{endpoint_id}`), raw JSON
    /// pass-through -- the recommended way to fetch a single device's detail
    /// (see module docs on why the generic trait method `get_system_details`
    /// alone isn't enough here: Action1's URL genuinely needs both IDs).
    /// `commands::action1` always has `organization_id` in scope already
    /// (from the org/device grouping it holds), so it calls this directly
    /// rather than going through the trait method's compound-string
    /// workaround.
    pub fn get_endpoint_details(
        &self,
        credentials: &PluginCredentials,
        organization_id: &str,
        endpoint_id: &str,
    ) -> Result<serde_json::Value, PluginError> {
        let creds = parse_credentials(credentials)?;
        let agent = build_agent();
        let token = fetch_access_token(&agent, &self.base_url, &creds)?;
        fetch_json(
            &agent,
            &format!(
                "{}/endpoints/managed/{organization_id}/{endpoint_id}",
                self.base_url.trim_end_matches('/')
            ),
            &token,
        )
    }
}

/// Checks a base URL/client ID/client secret triple against Action1 -- a
/// real OAuth2 token exchange, plus one lightweight follow-up call
/// (`GET /organizations`, a single page only, not a full `ResultPage` walk)
/// so a working token alone (e.g. against a wrong region host that happens
/// to still issue a token) doesn't get reported as success. Nothing is
/// persisted. For `commands::action1::test_action1_connection`, so users
/// notice a typo in the region/base URL/credentials before actually creating
/// a connection (writing credentials to the keyring) -- the same pattern as
/// `plugin::ninja::test_credentials`/`plugin::intune::test_credentials`.
pub fn test_credentials(
    base_url: &str,
    client_id: &str,
    client_secret: &str,
) -> Result<(), PluginError> {
    let creds = Action1Credentials {
        client_id: client_id.to_string(),
        client_secret: client_secret.to_string(),
    };
    let agent = build_agent();
    let token = fetch_access_token(&agent, base_url, &creds)?;
    let url = format!("{}/organizations", base_url.trim_end_matches('/'));
    fetch_json(&agent, &url, &token)?;
    Ok(())
}

impl Plugin for Action1Plugin {
    fn id(&self) -> &str {
        self.id.as_str()
    }

    fn list_systems(
        &self,
        credentials: &PluginCredentials,
    ) -> Result<Vec<ExternalSystem>, PluginError> {
        let (_organizations, endpoints) = self.list_organizations_with_endpoints(credentials)?;
        Ok(endpoints
            .into_iter()
            .map(|e| ExternalSystem {
                external_id: e.external_id,
                // Action1Endpoint has no separate hostname field (see its
                // own docs) -- `name` already holds the preferred
                // device_name/name fallback chain, so it doubles as both
                // here, the same convention `plugin::intune::IntuneDevice`
                // uses for `deviceName`.
                hostname: Some(e.name.clone()),
                name: e.name,
            })
            .collect())
    }

    fn get_system_details(
        &self,
        credentials: &PluginCredentials,
        external_id: &str,
    ) -> Result<serde_json::Value, PluginError> {
        // See module docs: the trait signature has no room for a separate
        // organization id, so this conformance path expects a
        // "<organization_id>:<endpoint_id>" compound external_id.
        // `commands::action1` never relies on this -- it calls
        // `get_endpoint_details` directly with the two IDs it already has.
        let (organization_id, endpoint_id) = split_compound_external_id(external_id)?;
        self.get_endpoint_details(credentials, organization_id, endpoint_id)
    }

    fn link_system(&self, local_system_id: i64, external_id: &str) -> Result<(), PluginError> {
        // Action1's API doesn't need to know anything about a local link --
        // purely a local bookkeeping concept, see trait documentation.
        // Persisted by the caller via `db::external_refs::upsert`.
        println!("Action1Plugin({}): verknüpfe lokales System {local_system_id} mit externer ID {external_id}", self.id);
        Ok(())
    }
}

fn parse_credentials(credentials: &PluginCredentials) -> Result<Action1Credentials, PluginError> {
    serde_json::from_str(&credentials.secret)
        .map_err(|e| PluginError::Authentication(format!("Action1-Zugangsdaten ungültig: {e}")))
}

/// Splits a `"<organization_id>:<endpoint_id>"` compound external ID (see
/// `Plugin::get_system_details` docs above). Pure function, testable without
/// any network access.
fn split_compound_external_id(external_id: &str) -> Result<(&str, &str), PluginError> {
    external_id.split_once(':').ok_or_else(|| {
        PluginError::UnexpectedResponse(
            "Externe Action1-ID im unerwarteten Format (erwartet '<organisation_id>:<endpunkt_id>')"
                .to_string(),
        )
    })
}

fn build_agent() -> Agent {
    let config = Agent::config_builder()
        .timeout_global(Some(Duration::from_secs(20)))
        .build();
    Agent::new_with_config(config)
}

/// Exchanges a client ID/secret pair for a bearer access token -- the JSON
/// variant (see module docs on the documented, unresolved disagreement with
/// Action1's own prose documentation).
fn fetch_access_token(
    agent: &Agent,
    base_url: &str,
    creds: &Action1Credentials,
) -> Result<String, PluginError> {
    let url = format!("{}/oauth2/token", base_url.trim_end_matches('/'));
    let body = TokenRequest {
        client_id: creds.client_id.as_str(),
        client_secret: creds.client_secret.as_str(),
    };
    let mut response = agent.post(&url).send_json(&body).map_err(map_ureq_error)?;
    let token: TokenResponse = response.body_mut().read_json().map_err(map_ureq_error)?;
    Ok(token.access_token)
}

/// Issues an authenticated `GET {url}` (Bearer token) and returns the parsed
/// JSON body.
fn fetch_json(
    agent: &Agent,
    url: &str,
    bearer_token: &str,
) -> Result<serde_json::Value, PluginError> {
    let mut response = agent
        .get(url)
        .header("Authorization", format!("Bearer {bearer_token}"))
        .call()
        .map_err(map_ureq_error)?;
    response
        .body_mut()
        .read_json::<serde_json::Value>()
        .map_err(map_ureq_error)
}

/// Walks one Action1 `ResultPage` resource end-to-end, starting at
/// `{base_url}{initial_path}` and following `next_page` (a relative URL,
/// see module docs) until it's absent/empty or `MAX_PAGES` is reached.
/// Returns the raw, un-mapped `items` of every page as one merged list.
fn fetch_all_pages(
    agent: &Agent,
    base_url: &str,
    initial_path: &str,
    token: &str,
) -> Result<Vec<serde_json::Value>, PluginError> {
    let mut all = Vec::new();
    let mut url = format!("{}{initial_path}", base_url.trim_end_matches('/'));
    for _ in 0..MAX_PAGES {
        let page = fetch_json(agent, &url, token)?;
        let (items, next_page) = parse_result_page(&page)?;
        all.extend(items);
        match next_page {
            Some(next) if !next.is_empty() => {
                url = format!("{}{next}", origin_of(base_url));
            }
            _ => break,
        }
    }
    Ok(all)
}

/// Extracts the `items` list and `next_page` continuation URL from a single
/// `ResultPage` response (see module docs for the full envelope shape).
/// Pure function, testable with hardcoded JSON, no network access needed --
/// analogous to `plugin::intune::parse_devices_page`. An empty-string
/// `next_page` is normalized away entirely (treated the same as an absent
/// field) here already, so `fetch_all_pages` only needs the single
/// `Some(next) if !next.is_empty()` check, not a duplicate one.
fn parse_result_page(
    json: &serde_json::Value,
) -> Result<(Vec<serde_json::Value>, Option<String>), PluginError> {
    let items = json["items"].as_array().ok_or_else(|| {
        PluginError::UnexpectedResponse("Erwartete 'items'-Liste in Action1-Antwort".to_string())
    })?;
    let next_page = json["next_page"]
        .as_str()
        .map(str::to_string)
        .filter(|s| !s.is_empty());
    Ok((items.clone(), next_page))
}

/// Extracts just the scheme+host portion of `base_url` (e.g.
/// `"https://app.action1.com"` from `"https://app.action1.com/api/3.0"`).
/// `next_page`/`prev_page` values are relative URLs that Action1's own docs
/// show starting fresh from the host root (example:
/// `/API/endpoints/managed?from=60&limit=10`, a different case/prefix than
/// `base_url`'s own `/api/3.0` suffix) -- so a follow-up request is built
/// from the origin alone, never by naively concatenating onto `base_url`
/// itself (which would risk a doubled or mismatched path prefix). Falls back
/// to the whole (trimmed) `base_url` if it doesn't look like `scheme://host/...`
/// at all, so a malformed/unusual `base_url` degrades instead of panicking.
fn origin_of(base_url: &str) -> String {
    if let Some(scheme_end) = base_url.find("://") {
        let after_scheme = scheme_end + 3;
        if let Some(host_end) = base_url[after_scheme..].find('/') {
            return base_url[..after_scheme + host_end].to_string();
        }
    }
    base_url.trim_end_matches('/').to_string()
}

fn map_ureq_error(e: ureq::Error) -> PluginError {
    match e {
        ureq::Error::StatusCode(code) if code == 401 || code == 403 => {
            PluginError::Authentication(format!("Action1-API antwortete mit Status {code}"))
        }
        ureq::Error::StatusCode(code) => {
            PluginError::Unreachable(format!("Action1-API antwortete mit Status {code}"))
        }
        ureq::Error::Json(err) => {
            PluginError::UnexpectedResponse(format!("Ungültige JSON-Antwort: {err}"))
        }
        other => PluginError::Unreachable(other.to_string()),
    }
}

/// Maps the raw `items` of a `GET /organizations` `ResultPage` walk to
/// `Action1Organization` values. Pure function, testable on its own with
/// hardcoded JSON, analogous to `plugin::ninja::map_organizations_response`.
fn map_organizations_response(
    items: &[serde_json::Value],
) -> Result<Vec<Action1Organization>, PluginError> {
    Ok(items.iter().filter_map(map_organization).collect())
}

/// A single organization object from Action1's `/organizations` response
/// (`{"id": ..., "name": "...", ...}`, see module docs on why `id`'s exact
/// JSON type is treated defensively -- string OR number both accepted,
/// mirroring `plugin::ninja::map_organization`'s handling of the same
/// documented uncertainty). If `id` is missing or has an unexpected shape ->
/// the organization is skipped instead of failing the whole call.
fn map_organization(value: &serde_json::Value) -> Option<Action1Organization> {
    let id = match &value["id"] {
        serde_json::Value::String(s) => s.clone(),
        serde_json::Value::Number(n) => n.to_string(),
        _ => return None,
    };
    let name = value["name"].as_str().unwrap_or(id.as_str()).to_string();
    Some(Action1Organization { id, name })
}

/// Maps the raw `items` of a `GET /endpoints/managed/{orgId}` `ResultPage`
/// walk to `Action1Endpoint` values, threading `organization_name` through
/// to every mapped endpoint (see `Action1Endpoint::organization_name`
/// docs). Pure function, testable on its own with hardcoded JSON.
fn map_endpoints_response(
    items: &[serde_json::Value],
    organization_name: Option<&str>,
) -> Vec<Action1Endpoint> {
    items
        .iter()
        .filter_map(|v| map_endpoint(v, organization_name))
        .collect()
}

/// A single endpoint object from Action1's `/endpoints/managed/{orgId}`
/// response (see module docs for the full verified field list). An endpoint
/// without a usable `id` OR without `organization_id` is skipped instead of
/// failing the whole call -- without organization membership it can't be
/// meaningfully grouped, and a single broken endpoint object shouldn't make
/// the whole list unusable, the same rule `plugin::ninja::map_ninja_device`
/// already applies. `device_name` is preferred for `name` (falling back to
/// `name`, then to the endpoint's own `id`), see module docs.
fn map_endpoint(
    value: &serde_json::Value,
    organization_name: Option<&str>,
) -> Option<Action1Endpoint> {
    let external_id = value["id"].as_str()?.to_string();
    let organization_id = value["organization_id"].as_str()?.to_string();
    let device_name = value["device_name"].as_str().map(str::to_string);
    let display_name = value["name"].as_str().map(str::to_string);
    let name = device_name
        .or(display_name)
        .unwrap_or_else(|| external_id.clone());
    let ip_address = value["address"].as_str().map(str::to_string);
    let status = value["status"].as_str().map(str::to_string);
    let platform = value["platform"].as_str().map(str::to_string);
    Some(Action1Endpoint {
        external_id,
        name,
        ip_address,
        status,
        platform,
        organization_id,
        organization_name: organization_name.map(str::to_string),
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    // Pins the exact JSON body shape the documented, unresolved disagreement
    // between Action1's prose docs and its Swagger spec required a ruling
    // on -- see module docs. If a real-world call later proves the
    // form-urlencoded prose variant correct instead, this test (and
    // `fetch_access_token`/`TokenRequest`) is the one place to fix.
    #[test]
    fn token_request_body_is_json_with_client_id_and_client_secret_only() {
        let body = TokenRequest {
            client_id: "abc",
            client_secret: "xyz",
        };
        let json = serde_json::to_value(&body).unwrap();
        assert_eq!(
            json,
            serde_json::json!({"client_id": "abc", "client_secret": "xyz"})
        );
        // Explicitly pin: exactly these two fields, no `grant_type` -- both
        // of Action1's own conflicting sources agree it's absent.
        assert_eq!(json.as_object().unwrap().len(), 2);
        assert!(!json.as_object().unwrap().contains_key("grant_type"));
    }

    #[test]
    fn parses_result_page_with_items_and_next_page() {
        let json = serde_json::json!({
            "id": "1", "type": "ResultPage", "items": [{"id": "org-1"}, {"id": "org-2"}],
            "total_items": 2, "limit": 10,
            "next_page": "/API/endpoints/managed?from=60&limit=10", "prev_page": ""
        });
        let (items, next_page) = parse_result_page(&json).unwrap();
        assert_eq!(items.len(), 2);
        assert_eq!(
            next_page.as_deref(),
            Some("/API/endpoints/managed?from=60&limit=10")
        );
    }

    #[test]
    fn parses_result_page_with_empty_string_next_page_as_last_page() {
        let json = serde_json::json!({"items": [], "next_page": ""});
        let (items, next_page) = parse_result_page(&json).unwrap();
        assert!(items.is_empty());
        assert_eq!(next_page, None);
    }

    #[test]
    fn parses_result_page_with_absent_next_page_as_last_page() {
        let json = serde_json::json!({"items": []});
        let (_items, next_page) = parse_result_page(&json).unwrap();
        assert_eq!(next_page, None);
    }

    #[test]
    fn result_page_rejects_missing_items_field() {
        let json = serde_json::json!({"next_page": ""});
        let result = parse_result_page(&json);
        assert!(matches!(result, Err(PluginError::UnexpectedResponse(_))));
    }

    #[test]
    fn origin_of_strips_the_api_path_suffix() {
        assert_eq!(
            origin_of("https://app.action1.com/api/3.0"),
            "https://app.action1.com"
        );
        assert_eq!(
            origin_of("https://app.eu.action1.com/api/3.0/"),
            "https://app.eu.action1.com"
        );
    }

    #[test]
    fn origin_of_falls_back_to_trimmed_input_without_a_path() {
        assert_eq!(
            origin_of("https://app.action1.com"),
            "https://app.action1.com"
        );
    }

    #[test]
    fn maps_organizations_json_items_into_action1_organizations() {
        let items = vec![
            serde_json::json!({"id": "org-1", "name": "ACME Hauptsitz"}),
            serde_json::json!({"id": "org-2", "name": "ACME Zweigstelle"}),
        ];
        let organizations = map_organizations_response(&items).unwrap();
        assert_eq!(organizations.len(), 2);
        assert_eq!(
            organizations[0],
            Action1Organization {
                id: "org-1".to_string(),
                name: "ACME Hauptsitz".to_string()
            }
        );
    }

    #[test]
    fn organization_accepts_numeric_id_defensively() {
        let items = vec![serde_json::json!({"id": 1, "name": "ACME"})];
        let organizations = map_organizations_response(&items).unwrap();
        assert_eq!(organizations[0].id, "1");
    }

    #[test]
    fn organization_falls_back_to_id_when_no_name_field_present() {
        let items = vec![serde_json::json!({"id": "org-9"})];
        let organizations = map_organizations_response(&items).unwrap();
        assert_eq!(organizations[0].name, "org-9");
    }

    #[test]
    fn organization_skips_entries_without_a_usable_id() {
        let items = vec![serde_json::json!({"name": "OhneId"})];
        let organizations = map_organizations_response(&items).unwrap();
        assert!(organizations.is_empty());
    }

    #[test]
    fn maps_endpoints_json_items_with_organization_id_and_status() {
        let items = vec![
            serde_json::json!({
                "id": "ep-1",
                "device_name": "SRV-01",
                "name": "Server 01 (Buchhaltung)",
                "address": "10.0.0.5",
                "status": "Connected",
                "platform": "Windows",
                "organization_id": "11111111-1111-1111-1111-111111111111",
                "online_status": "ERROR"
            }),
            serde_json::json!({
                "id": "ep-2",
                "address": "10.0.0.6",
                "status": "Disconnected",
                "organization_id": "22222222-2222-2222-2222-222222222222"
            }),
        ];
        let endpoints = map_endpoints_response(&items, Some("ACME Hauptsitz"));

        assert_eq!(endpoints.len(), 2);
        assert_eq!(endpoints[0].external_id, "ep-1");
        // device_name preferred over the separate, user-editable `name`.
        assert_eq!(endpoints[0].name, "SRV-01");
        assert_eq!(endpoints[0].ip_address.as_deref(), Some("10.0.0.5"));
        assert_eq!(endpoints[0].status.as_deref(), Some("Connected"));
        assert_eq!(endpoints[0].platform.as_deref(), Some("Windows"));
        assert_eq!(
            endpoints[0].organization_id,
            "11111111-1111-1111-1111-111111111111"
        );
        assert_eq!(
            endpoints[0].organization_name.as_deref(),
            Some("ACME Hauptsitz")
        );

        // No device_name here -> falls back to the endpoint's own `id`
        // (no `name` field present either in this fixture).
        assert_eq!(endpoints[1].external_id, "ep-2");
        assert_eq!(endpoints[1].name, "ep-2");
        assert_eq!(endpoints[1].status.as_deref(), Some("Disconnected"));
    }

    #[test]
    fn endpoint_falls_back_to_display_name_when_no_device_name_present() {
        let items = vec![serde_json::json!({
            "id": "ep-3", "name": "Laptop von Anna", "organization_id": "org-1"
        })];
        let endpoints = map_endpoints_response(&items, None);
        assert_eq!(endpoints[0].name, "Laptop von Anna");
    }

    #[test]
    fn endpoint_skips_entries_without_a_usable_id() {
        let items = vec![serde_json::json!({"organization_id": "org-1"})];
        let endpoints = map_endpoints_response(&items, None);
        assert!(endpoints.is_empty());
    }

    #[test]
    fn endpoint_skips_entries_without_organization_id() {
        let items = vec![serde_json::json!({"id": "ep-1"})];
        let endpoints = map_endpoints_response(&items, None);
        assert!(endpoints.is_empty());
    }

    #[test]
    fn endpoint_organization_name_is_none_when_not_supplied() {
        let items = vec![serde_json::json!({"id": "ep-1", "organization_id": "org-1"})];
        let endpoints = map_endpoints_response(&items, None);
        assert_eq!(endpoints[0].organization_name, None);
    }

    #[test]
    fn splits_compound_external_id_into_organization_and_endpoint() {
        let (org, ep) = split_compound_external_id("org-1:ep-9").unwrap();
        assert_eq!(org, "org-1");
        assert_eq!(ep, "ep-9");
    }

    #[test]
    fn split_compound_external_id_rejects_missing_separator() {
        let result = split_compound_external_id("no-separator-here");
        assert!(matches!(result, Err(PluginError::UnexpectedResponse(_))));
    }

    #[test]
    fn maps_401_status_to_authentication_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(401));
        assert!(matches!(err, PluginError::Authentication(_)));
    }

    #[test]
    fn maps_403_status_to_authentication_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(403));
        assert!(matches!(err, PluginError::Authentication(_)));
    }

    #[test]
    fn maps_other_status_codes_to_unreachable_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(500));
        assert!(matches!(err, PluginError::Unreachable(_)));
    }

    #[test]
    fn maps_429_status_to_unreachable_error() {
        // Action1's own rate-limit response (see module docs) -- not an
        // Authentication failure, so it's correctly routed to Unreachable
        // like every other non-401/403 status code, allowing the user to
        // distinguish "wrong credentials" from "try again shortly".
        let err = map_ureq_error(ureq::Error::StatusCode(429));
        assert!(matches!(err, PluginError::Unreachable(_)));
    }

    #[test]
    fn parses_credentials_from_json_secret() {
        let creds = PluginCredentials {
            secret: r#"{"client_id":"abc","client_secret":"xyz"}"#.into(),
        };
        let parsed = parse_credentials(&creds).unwrap();
        assert_eq!(parsed.client_id, "abc");
        assert_eq!(parsed.client_secret, "xyz");
    }

    #[test]
    fn rejects_malformed_credentials_json() {
        let creds = PluginCredentials {
            secret: "not json".into(),
        };
        let result = parse_credentials(&creds);
        assert!(matches!(result, Err(PluginError::Authentication(_))));
    }

    #[test]
    fn plugin_id_returns_configured_connection_id() {
        let plugin = Action1Plugin::new(
            "action1:acme-123".to_string(),
            "https://app.action1.com/api/3.0".to_string(),
        );
        assert_eq!(plugin.id(), "action1:acme-123");
    }
}
