//! Real plugin implementation for Atera (cloud-hosted RMM/PSA for MSPs,
//! <https://www.atera.com/>), see `docs/PLUGIN_ARCHITECTURE.md` section
//! "Atera-Plugin". Ninth real integration, after NinjaOne (`plugin::ninja`),
//! Level.io (`plugin::level`), Snipe-IT (`plugin::snipeit`), Microsoft
//! Intune (`plugin::intune`), Iru/Kandji (`plugin::iru`), Jamf Pro
//! (`plugin::jamf`), Apple Business Manager (`plugin::abm`) and Tactical RMM
//! (`plugin::tacticalrmm`). Combines two patterns already used elsewhere in
//! this codebase rather than introducing a new one:
//!
//! - Like Level.io (`plugin::level`) and UNLIKE Tactical RMM/NinjaOne/
//!   Snipe-IT: Atera is a single, fixed cloud host, not self-hosted -- no
//!   user-supplied `base_url` field on `AteraConnectionMeta`, just the
//!   constant `BASE_URL` below.
//! - Like Tactical RMM (`plugin::tacticalrmm`) and NinjaOne
//!   (`plugin::ninja`), and UNLIKE Level.io: Atera models a genuine
//!   multi-tenant hierarchy within a single connection ("Customer" ->
//!   "Agent") -- a single connection (one API key) can see multiple
//!   Customers, each individually mapped to a local customer via
//!   `AteraCustomerMapping`/`Config::atera_customer_mappings`, exactly the
//!   same connection+mapping-table shape as
//!   `TacticalRmmConnectionMeta`/`TacticalRmmClientMapping`.
//!
//! Every fact below comes from the task brief for this integration, itself
//! already verified against Atera's own official API documentation (not
//! re-derived or guessed here):
//!
//! - **Authentication**: a static API key in a custom `X-API-KEY` header
//!   (NOT `Authorization: Bearer`) -- the same header name/convention as
//!   Tactical RMM, generated by the user in Atera's own web UI (Admin ->
//!   Data Management -> API). A single secret value, passed through 1:1 as
//!   `PluginCredentials.secret`, like Tactical RMM/Level.io/Snipe-IT -- no
//!   JSON encoding of multiple values needed (unlike NinjaOne).
//! - **Base URL**: fixed, single SaaS host, `https://app.atera.com/api/v3`
//!   (`BASE_URL` below) -- like `plugin::level::BASE_URL`, no
//!   per-connection configurability, no region/instance variants.
//! - **Customers (multi-tenancy)**: `GET /customers`, a PAGINATED envelope
//!   (camelCase envelope keys, PascalCase item fields -- genuinely
//!   different casing conventions in the same response, not a typo):
//!   `{"items": [{"CustomerID": <number>, "CustomerName": "...", ...}],
//!   "page": <number>, "itemsInPage": <number>, "totalPages": <number>,
//!   "totalItemCount": <number>, "nextLink": "..."}`. Unlike Tactical RMM's
//!   bare, unpaginated `/clients/` array, this needs a real pagination loop
//!   -- `fetch_all_pages` below walks `page`/`totalPages` (not `nextLink`,
//!   simpler and equally correct: `nextLink` is just
//!   `?page=<page+1>&itemsInPage=<itemsInPage>` reconstructed) until
//!   `page >= totalPages`, using `itemsInPage=50` (the documented maximum)
//!   throughout.
//! - **Agents (NOT "Devices")**: `GET /agents`, the SAME paginated envelope
//!   shape as `/customers` -- Atera's "Devices" is a separate SNMP/
//!   network-monitoring concept, deliberately not used here. Item fields
//!   (`AgentQueryDTO`, PascalCase): `AgentID` (number, used as
//!   `external_id`, stringified), `MachineName` (string, hostname/display
//!   name), `IpAddresses` (a real JSON ARRAY of local IPs, unlike Tactical
//!   RMM's comma-separated string -- `extract_ip_address` below is simpler
//!   because of this), `ReportedFromIP` (string, public/external IP
//!   fallback), `Online` (bool, mapped to the string convention
//!   `"online"`/`"offline"` used elsewhere in this codebase, e.g.
//!   `plugin::tacticalrmm`), `OS` (string, platform/OS display text),
//!   `CustomerID` (number) -- a GENUINE numeric foreign key directly on the
//!   agent, unlike Tactical RMM's name-only client join (see
//!   `plugin::tacticalrmm` module docs) -- grouping by customer here uses a
//!   real ID join, exactly like `plugin::ninja`'s `organizationId`, not a
//!   name-matching workaround. `CustomerName` (string, for display).
//! - **Single agent detail**: `GET /agents/{agentId}`.
//! - **No verified dashboard deep-link format**: the schema carries an
//!   `AppViewUrl` field on the agent object per Atera's own API, but its
//!   exact URL shape wasn't independently confirmed. `map_agent` below
//!   passes it through AS-IS if present (`AteraAgent.view_url`), but never
//!   hand-constructs a URL when it's absent -- the same "honest omission"
//!   principle as Tactical RMM's missing `tacticalrmm_url` (see
//!   `plugin::tacticalrmm` module docs on why), just resolved per-agent
//!   here instead of leaving the field out of the type entirely, since
//!   Atera itself sometimes DOES provide it.
//! - **Rate limits**: not documented officially by Atera -- no special
//!   handling added (no backoff/retry), the same "not documented, so not
//!   guessed at" stance `plugin::tacticalrmm`'s module docs take on rate
//!   limits.
//! - **HTTP client**: `ureq` 3.4.1, synchronous, the same dependency as
//!   every other plugin in this codebase.

use std::time::Duration;

use serde::{Deserialize, Serialize};
use ureq::Agent;

use super::{ExternalSystem, Plugin, PluginCredentials, PluginError};

/// Fixed, single SaaS host -- unlike NinjaOne/Snipe-IT/Tactical RMM, Atera
/// has no self-hosted/region-specific variant, so a Rust constant is enough,
/// analogous to `plugin::level::BASE_URL`.
pub const BASE_URL: &str = "https://app.atera.com/api/v3";

/// The documented maximum page size for Atera's paginated endpoints (see
/// module docs). Used on every page request, including `test_credentials`,
/// which deliberately overrides it down to `1` for a minimal, lightweight
/// call.
const ITEMS_PER_PAGE: u32 = 50;

/// Safety brake against a misbehaving remote end (e.g. `totalPages` stuck
/// above reality, or an infinite loop from a broken response) -- analogous
/// to `plugin::level::MAX_PAGES`, just walking a page NUMBER instead of a
/// cursor.
const MAX_PAGES: u32 = 200;

/// Non-secret metadata of an Atera connection, as stored in `config.toml`
/// (`Config::atera_connections`). The API key belongs, per the credential
/// principle, exclusively in the OS keyring, never here. Deliberately
/// WITHOUT a `base_url` field -- unlike `TacticalRmmConnectionMeta`, Atera
/// is a single fixed SaaS host (see `BASE_URL` above), so there is nothing
/// for the user to supply beyond the API key itself. Also deliberately
/// WITHOUT `customer_id` -- a connection is an Atera account, not a local
/// customer; which Atera "Customer" within this account corresponds to
/// which local customer is tracked granularly in
/// `AteraCustomerMapping`/`Config::atera_customer_mappings`, exactly the
/// same principle as `plugin::tacticalrmm::TacticalRmmConnectionMeta`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AteraConnectionMeta {
    pub id: String,
    pub label: String,
}

/// Mapping of a single Atera "Customer" (within a connection) to a local
/// customer. Lives in `Config::atera_customer_mappings`, not in
/// `AteraConnectionMeta` -- a connection can see multiple Customers, each of
/// which can be mapped independently (or left unmapped). `customer_id` is
/// the real, numeric Atera Customer ID (as a string, from `GET /customers`,
/// `CustomerID`); `customer_name` is stored alongside it so a UI list can
/// display a readable name without another live call against Atera.
/// `local_customer_id` (deliberately not just `customer_id`, to avoid
/// confusing Atera's own "Customer" concept with this app's local
/// `Customer` entity) is the local, mapped customer -- analogous to
/// `plugin::tacticalrmm::TacticalRmmClientMapping.customer_id`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AteraCustomerMapping {
    pub connection_id: String,
    pub customer_id: String,
    pub customer_name: String,
    pub local_customer_id: i64,
}

/// A customer reported by `GET /customers`. Separate from `ExternalSystem`
/// (those are agents) -- its own, small shape type, analogous to
/// `plugin::tacticalrmm::TacticalRmmClient`/`plugin::ninja::NinjaOrganization`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AteraCustomer {
    pub id: String,
    pub name: String,
}

/// A single agent from `GET /agents` (or `GET /agents/{agentId}`), enriched
/// with the verified extra fields `plugin::mod::ExternalSystem` deliberately
/// does not provide (status, platform, the owning customer, and the
/// optional dashboard link). Needed by `commands::atera::sync_atera_connection`
/// for grouping by customer and for display, analogous to
/// `plugin::tacticalrmm::TacticalRmmAgent`/`plugin::ninja::NinjaDevice`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AteraAgent {
    pub external_id: String,
    pub name: String,
    pub hostname: Option<String>,
    pub ip_address: Option<String>,
    /// `"online"`/`"offline"`, derived from Atera's boolean `Online` field
    /// (see module docs) -- kept as a free-form string, not a bool, to match
    /// the string convention every other plugin in this codebase uses for
    /// agent status (e.g. `plugin::tacticalrmm::TacticalRmmAgent::status`).
    pub status: Option<String>,
    /// Atera's own `OS` display string, passed through verbatim -- unlike
    /// Tactical RMM's `plat`, this is not a small closed set of verified
    /// constants, just free display text, so there is no Rust enum to
    /// misparse a future value.
    pub platform: Option<String>,
    /// The agent's owning Atera Customer, as a real numeric ID (stringified)
    /// -- a genuine foreign key, unlike Tactical RMM's name-only join (see
    /// module docs). Used as the join key in
    /// `commands::atera::group_agents_by_customer`.
    pub customer_id: String,
    pub customer_name: String,
    /// Direct link to this agent in Atera's web UI, if Atera's own API
    /// provided one (`AppViewUrl`) -- `None` if the field was absent, NEVER
    /// hand-constructed from other data (see module docs on why the exact
    /// URL shape isn't verified).
    pub view_url: Option<String>,
}

/// A plugin object for exactly one configured Atera connection. `id` here is
/// already the fully qualified identifier (`"atera:<connection_id>"`), so
/// that `Plugin::id()` works unmodified as the `plugin_id`/keyring account
/// (see trait documentation in `plugin::mod`). Unlike `TacticalRmmPlugin`,
/// this type needs no `base_url` field (see `BASE_URL` above) -- the API key
/// comes fresh from `PluginCredentials` on every call, same as
/// `plugin::level::LevelPlugin`.
pub struct AteraPlugin {
    id: String,
}

impl AteraPlugin {
    pub fn new(id: String) -> Self {
        Self { id }
    }

    /// Live fetch of this connection's ENTIRE customer list (`GET
    /// /customers`), with pagination walked internally (see module
    /// documentation). Separate from the `Plugin` trait method
    /// `list_systems`, because customers are not agents and the generic
    /// trait has no room for that -- analogous to
    /// `plugin::tacticalrmm::TacticalRmmPlugin::list_clients`.
    pub fn list_customers(
        &self,
        credentials: &PluginCredentials,
    ) -> Result<Vec<AteraCustomer>, PluginError> {
        let agent = build_agent();
        let raw = fetch_all_pages(&agent, &credentials.secret, "/customers")?;
        Ok(map_customers(&raw))
    }

    /// Live fetch of ALL this connection's agents (`GET /agents`), with
    /// pagination walked internally, same as `list_customers`. Richer than
    /// the trait method `list_systems`, which deliberately stays with the
    /// narrow, plugin-agnostic `ExternalSystem` type (no `status`/
    /// `platform`/`customer_id`/`customer_name`/`view_url` field there).
    pub fn list_agents(
        &self,
        credentials: &PluginCredentials,
    ) -> Result<Vec<AteraAgent>, PluginError> {
        let agent = build_agent();
        let raw = fetch_all_pages(&agent, &credentials.secret, "/agents")?;
        Ok(map_agents(&raw))
    }
}

/// Checks an API key against Atera (a lightweight, real call: `GET
/// /customers?page=1&itemsInPage=1`, deliberately just one item, not the
/// full paginated collection `list_customers` would fetch), without
/// persisting anything. For `commands::atera::test_atera_connection`, so
/// users notice a typo in the API key before actually creating a connection
/// (writing credentials to the keyring) -- exactly the same pattern as
/// `plugin::tacticalrmm::test_credentials`/`plugin::level::test_credentials`.
pub fn test_credentials(api_key: &str) -> Result<(), PluginError> {
    let agent = build_agent();
    let url = format!("{BASE_URL}/customers");
    let mut response = agent
        .get(&url)
        .header("X-API-KEY", api_key)
        .query("page", "1")
        .query("itemsInPage", "1")
        .call()
        .map_err(map_ureq_error)?;
    response
        .body_mut()
        .read_json::<serde_json::Value>()
        .map_err(map_ureq_error)?;
    Ok(())
}

impl Plugin for AteraPlugin {
    fn id(&self) -> &str {
        self.id.as_str()
    }

    fn list_systems(
        &self,
        credentials: &PluginCredentials,
    ) -> Result<Vec<ExternalSystem>, PluginError> {
        let agents = self.list_agents(credentials)?;
        Ok(agents
            .into_iter()
            .map(|a| ExternalSystem {
                external_id: a.external_id,
                name: a.name,
                hostname: a.hostname,
            })
            .collect())
    }

    fn get_system_details(
        &self,
        credentials: &PluginCredentials,
        external_id: &str,
    ) -> Result<serde_json::Value, PluginError> {
        let agent = build_agent();
        let url = format!("{BASE_URL}/agents/{external_id}");
        let mut response = agent
            .get(&url)
            .header("X-API-KEY", &credentials.secret)
            .call()
            .map_err(map_ureq_error)?;
        response
            .body_mut()
            .read_json::<serde_json::Value>()
            .map_err(map_ureq_error)
    }

    fn link_system(&self, local_system_id: i64, external_id: &str) -> Result<(), PluginError> {
        // Atera's API doesn't need to know anything about a local link --
        // purely a local bookkeeping concept, see trait documentation.
        // Persisted by the caller via `db::external_refs::upsert`.
        println!("AteraPlugin({}): verknüpfe lokales System {local_system_id} mit externer ID {external_id}", self.id);
        Ok(())
    }
}

fn build_agent() -> Agent {
    let config = Agent::config_builder()
        .timeout_global(Some(Duration::from_secs(20)))
        .build();
    Agent::new_with_config(config)
}

/// Issues a single authenticated `GET {BASE_URL}{path}?page=<page>&itemsInPage=<ITEMS_PER_PAGE>`
/// and returns the parsed JSON page envelope. Auth header is `X-API-KEY`
/// (see module docs), NOT `Authorization: Bearer` like NinjaOne/Snipe-IT.
fn fetch_page_json(
    agent: &Agent,
    api_key: &str,
    path: &str,
    page: u32,
) -> Result<serde_json::Value, PluginError> {
    let url = format!("{BASE_URL}{path}");
    let mut response = agent
        .get(&url)
        .header("X-API-KEY", api_key)
        .query("page", page.to_string())
        .query("itemsInPage", ITEMS_PER_PAGE.to_string())
        .call()
        .map_err(map_ureq_error)?;
    response
        .body_mut()
        .read_json::<serde_json::Value>()
        .map_err(map_ureq_error)
}

/// Fetches every page of a paginated Atera endpoint (`/customers` or
/// `/agents`, same envelope shape, see module docs) and returns the merged
/// item list. Walks `page`/`totalPages` (see `parse_page_envelope`) instead
/// of following `nextLink` -- equivalent and simpler, since `nextLink` is
/// just `page + 1` with the same `itemsInPage`. Stops once `page >=
/// totalPages`, or after `MAX_PAGES` as a safety brake against a
/// misbehaving remote end (see module docs). Deliberately just collects the
/// raw page envelopes and hands them to `collect_pages` -- the actual
/// item-merging logic -- so that pure function is exercised by BOTH
/// production code and tests, not a parallel, potentially-drifting
/// reimplementation for tests only.
fn fetch_all_pages(
    agent: &Agent,
    api_key: &str,
    path: &str,
) -> Result<Vec<serde_json::Value>, PluginError> {
    let mut raw_pages = Vec::new();
    let mut page_num: u32 = 1;
    loop {
        let page_json = fetch_page_json(agent, api_key, path, page_num)?;
        let (_, page, total_pages) = parse_page_envelope(&page_json)?;
        raw_pages.push(page_json);
        if page >= total_pages || page_num >= MAX_PAGES {
            break;
        }
        page_num += 1;
    }
    collect_pages(&raw_pages)
}

fn map_ureq_error(e: ureq::Error) -> PluginError {
    match e {
        ureq::Error::StatusCode(code) if code == 401 || code == 403 => {
            PluginError::Authentication(format!("Atera-API antwortete mit Status {code}"))
        }
        ureq::Error::StatusCode(code) => {
            PluginError::Unreachable(format!("Atera-API antwortete mit Status {code}"))
        }
        ureq::Error::Json(err) => {
            PluginError::UnexpectedResponse(format!("Ungültige JSON-Antwort: {err}"))
        }
        other => PluginError::Unreachable(other.to_string()),
    }
}

/// Parses a single Atera page envelope (`{"items": [...], "page": N,
/// "totalPages": N, ...}`, see module docs) into its items array plus the
/// current/total page numbers. Pure function, testable with hardcoded JSON,
/// no real network access needed. `page`/`totalPages` default to `1` if
/// missing/non-numeric -- treated as "this is the only page" rather than
/// failing the whole call, since only `items` is strictly required to make
/// any use of a page at all.
fn parse_page_envelope(
    json: &serde_json::Value,
) -> Result<(Vec<serde_json::Value>, u64, u64), PluginError> {
    let items = json["items"].as_array().ok_or_else(|| {
        PluginError::UnexpectedResponse("Erwartete 'items'-Liste in Atera-Antwort".to_string())
    })?;
    let page = json["page"].as_u64().unwrap_or(1);
    let total_pages = json["totalPages"].as_u64().unwrap_or(page);
    Ok((items.clone(), page, total_pages))
}

/// Merges a list of already-fetched Atera page envelopes (in fetch order)
/// into one flat `Vec` of raw item JSON values. Pure, testable by
/// hand-building JSON pages instead of exercising the live GET loop -- also
/// the exact function `fetch_all_pages` itself calls, so tests and
/// production share one code path. Analogous to `plugin::level`'s
/// `parse_devices_page`/`parse_groups_page` split out of
/// `fetch_all_devices`/`fetch_all_groups`.
fn collect_pages(pages: &[serde_json::Value]) -> Result<Vec<serde_json::Value>, PluginError> {
    let mut all = Vec::new();
    for page in pages {
        let (items, _, _) = parse_page_envelope(page)?;
        all.extend(items);
    }
    Ok(all)
}

/// Maps the merged item list from `GET /customers` to `AteraCustomer`
/// values. Pure function, testable on its own with hardcoded JSON, no
/// network access needed.
fn map_customers(items: &[serde_json::Value]) -> Vec<AteraCustomer> {
    items.iter().filter_map(map_customer).collect()
}

/// A single customer object from Atera's `/customers` response
/// (`{"CustomerID": <number>, "CustomerName": "...", ...}`, PascalCase, see
/// module docs). If `CustomerID` is missing or has an unexpected shape ->
/// the customer is skipped instead of failing the whole call, analogous to
/// `plugin::tacticalrmm::map_client`/`plugin::ninja::map_organization`.
fn map_customer(value: &serde_json::Value) -> Option<AteraCustomer> {
    let id = match &value["CustomerID"] {
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::String(s) => s.clone(),
        _ => return None,
    };
    let name = value["CustomerName"]
        .as_str()
        .unwrap_or(id.as_str())
        .to_string();
    Some(AteraCustomer { id, name })
}

/// Maps the merged item list from `GET /agents` to `AteraAgent` values.
/// Pure function, testable on its own with hardcoded JSON, analogous to
/// `map_customers`.
fn map_agents(items: &[serde_json::Value]) -> Vec<AteraAgent> {
    items.iter().filter_map(map_agent).collect()
}

/// A single agent object from Atera's `/agents` response (`AgentQueryDTO`,
/// PascalCase, verified field list: `AgentID`, `MachineName`,
/// `IpAddresses`, `ReportedFromIP`, `Online`, `OS`, `CustomerID`,
/// `CustomerName`, `AppViewUrl` -- see module docs). An agent without a
/// usable `AgentID` OR without a usable `CustomerID` is skipped -- without
/// customer membership it can't be meaningfully grouped (see module docs on
/// the genuine ID-based join), and a single broken agent object shouldn't
/// make the whole list unusable, analogous to
/// `plugin::ninja::map_ninja_device`'s "skip without organizationId" rule.
fn map_agent(value: &serde_json::Value) -> Option<AteraAgent> {
    let external_id = match &value["AgentID"] {
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::String(s) => s.clone(),
        _ => return None,
    };
    let customer_id = match &value["CustomerID"] {
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::String(s) => s.clone(),
        _ => return None,
    };
    let customer_name = value["CustomerName"]
        .as_str()
        .unwrap_or(customer_id.as_str())
        .to_string();
    let hostname = value["MachineName"].as_str().map(str::to_string);
    let name = hostname.clone().unwrap_or_else(|| external_id.clone());
    let status = value["Online"]
        .as_bool()
        .map(|online| if online { "online" } else { "offline" }.to_string());
    let platform = value["OS"].as_str().map(str::to_string);
    let ip_address = extract_ip_address(value);
    let view_url = value["AppViewUrl"].as_str().map(str::to_string);
    Some(AteraAgent {
        external_id,
        name,
        hostname,
        ip_address,
        status,
        platform,
        customer_id,
        customer_name,
        view_url,
    })
}

/// Extracts a display IP address for an agent. `IpAddresses` is a real JSON
/// array of local IP strings (verified, see module docs -- unlike Tactical
/// RMM's comma-separated `local_ips` string); the first NON-EMPTY entry is
/// used. `ReportedFromIP` (the public/external IP, a plain string field) is
/// the fallback if `IpAddresses` is missing/empty/only-empty-strings --
/// mirroring the "primary + fallback" convention already used by
/// `plugin::tacticalrmm::extract_ip_address`/`plugin::ninja::map_ninja_device`,
/// just adapted to Atera's simpler, genuinely-array shape.
fn extract_ip_address(value: &serde_json::Value) -> Option<String> {
    let from_local = value["IpAddresses"].as_array().and_then(|addresses| {
        addresses
            .iter()
            .filter_map(|a| a.as_str())
            .find(|s| !s.is_empty())
            .map(str::to_string)
    });
    from_local.or_else(|| {
        value["ReportedFromIP"]
            .as_str()
            .filter(|s| !s.is_empty())
            .map(str::to_string)
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn page_envelope(items: serde_json::Value, page: u64, total_pages: u64) -> serde_json::Value {
        serde_json::json!({
            "items": items,
            "page": page,
            "itemsInPage": 50,
            "totalPages": total_pages,
            "totalItemCount": 0,
            "nextLink": serde_json::Value::Null,
        })
    }

    #[test]
    fn parse_page_envelope_extracts_items_page_and_total_pages() {
        let json = page_envelope(serde_json::json!([{"CustomerID": 1}, {"CustomerID": 2}]), 1, 3);
        let (items, page, total_pages) = parse_page_envelope(&json).unwrap();
        assert_eq!(items.len(), 2);
        assert_eq!(page, 1);
        assert_eq!(total_pages, 3);
    }

    #[test]
    fn parse_page_envelope_rejects_missing_items_field() {
        let json = serde_json::json!({"page": 1, "totalPages": 1});
        let result = parse_page_envelope(&json);
        assert!(matches!(result, Err(PluginError::UnexpectedResponse(_))));
    }

    #[test]
    fn parse_page_envelope_defaults_page_and_total_pages_when_missing() {
        let json = serde_json::json!({"items": []});
        let (items, page, total_pages) = parse_page_envelope(&json).unwrap();
        assert!(items.is_empty());
        assert_eq!(page, 1);
        assert_eq!(total_pages, 1);
    }

    #[test]
    fn collect_pages_merges_items_across_multiple_pages() {
        let pages = vec![
            page_envelope(serde_json::json!([{"CustomerID": 1}, {"CustomerID": 2}]), 1, 2),
            page_envelope(serde_json::json!([{"CustomerID": 3}]), 2, 2),
        ];
        let items = collect_pages(&pages).unwrap();
        assert_eq!(items.len(), 3);
        assert_eq!(items[2]["CustomerID"], 3);
    }

    #[test]
    fn collect_pages_propagates_error_from_a_bad_page() {
        let pages = vec![serde_json::json!({"no_items_field": true})];
        let result = collect_pages(&pages);
        assert!(matches!(result, Err(PluginError::UnexpectedResponse(_))));
    }

    #[test]
    fn maps_customers_json_items_into_atera_customers() {
        let items = serde_json::json!([
            {"CustomerID": 42, "CustomerName": "Acme Corp"},
            {"CustomerID": 7, "CustomerName": "Contoso AG"}
        ]);
        let customers = map_customers(items.as_array().unwrap());

        assert_eq!(customers.len(), 2);
        assert_eq!(
            customers[0],
            AteraCustomer {
                id: "42".to_string(),
                name: "Acme Corp".to_string()
            }
        );
        assert_eq!(customers[1].id, "7");
        assert_eq!(customers[1].name, "Contoso AG");
    }

    #[test]
    fn customer_falls_back_to_id_when_no_name_field_present() {
        let items = serde_json::json!([{"CustomerID": 9}]);
        let customers = map_customers(items.as_array().unwrap());
        assert_eq!(customers[0].name, "9");
    }

    #[test]
    fn customer_skips_entries_without_a_usable_id() {
        let items = serde_json::json!([{"CustomerName": "OhneId"}]);
        let customers = map_customers(items.as_array().unwrap());
        assert!(customers.is_empty());
    }

    #[test]
    fn maps_agents_json_items_with_status_platform_customer_and_ip() {
        let items = serde_json::json!([
            {
                "AgentID": 501,
                "MachineName": "SRV-01",
                "CustomerID": 42,
                "CustomerName": "Acme Corp",
                "Online": true,
                "OS": "Windows Server 2022",
                "IpAddresses": ["10.0.0.5", "10.0.0.6"],
                "ReportedFromIP": "203.0.113.9",
                "AppViewUrl": "https://app.atera.com/agent/501"
            },
            {
                "AgentID": 502,
                "MachineName": "WS-07",
                "CustomerID": 7,
                "CustomerName": "Contoso AG",
                "Online": false,
                "OS": "macOS 14",
                "IpAddresses": [],
                "ReportedFromIP": null
            }
        ]);

        let agents = map_agents(items.as_array().unwrap());

        assert_eq!(agents.len(), 2);
        assert_eq!(agents[0].external_id, "501");
        assert_eq!(agents[0].name, "SRV-01");
        assert_eq!(agents[0].hostname.as_deref(), Some("SRV-01"));
        assert_eq!(agents[0].customer_id, "42");
        assert_eq!(agents[0].customer_name, "Acme Corp");
        assert_eq!(agents[0].status.as_deref(), Some("online"));
        assert_eq!(agents[0].platform.as_deref(), Some("Windows Server 2022"));
        assert_eq!(agents[0].ip_address.as_deref(), Some("10.0.0.5"));
        assert_eq!(
            agents[0].view_url.as_deref(),
            Some("https://app.atera.com/agent/501")
        );
        assert_eq!(agents[1].external_id, "502");
        assert_eq!(agents[1].customer_id, "7");
        assert_eq!(agents[1].status.as_deref(), Some("offline"));
        assert_eq!(agents[1].ip_address, None);
        assert_eq!(agents[1].view_url, None);
    }

    #[test]
    fn agent_skips_entries_without_agent_id() {
        let items = serde_json::json!([{"MachineName": "OhneId", "CustomerID": 1}]);
        let agents = map_agents(items.as_array().unwrap());
        assert!(agents.is_empty());
    }

    #[test]
    fn agent_skips_entries_without_customer_id() {
        let items = serde_json::json!([{"AgentID": 1, "MachineName": "OhneKunde"}]);
        let agents = map_agents(items.as_array().unwrap());
        assert!(agents.is_empty());
    }

    #[test]
    fn agent_falls_back_to_external_id_when_no_machine_name_present() {
        let items = serde_json::json!([{"AgentID": 501, "CustomerID": 42}]);
        let agents = map_agents(items.as_array().unwrap());
        assert_eq!(agents[0].name, "501");
        assert_eq!(agents[0].hostname, None);
    }

    #[test]
    fn agent_falls_back_to_customer_id_when_no_customer_name_present() {
        let items = serde_json::json!([{"AgentID": 501, "CustomerID": 42}]);
        let agents = map_agents(items.as_array().unwrap());
        assert_eq!(agents[0].customer_name, "42");
    }

    #[test]
    fn agent_status_is_none_when_online_field_missing() {
        let items = serde_json::json!([{"AgentID": 501, "CustomerID": 42}]);
        let agents = map_agents(items.as_array().unwrap());
        assert_eq!(agents[0].status, None);
    }

    #[test]
    fn extract_ip_address_prefers_first_non_empty_local_ip() {
        let value = serde_json::json!({
            "IpAddresses": ["10.0.0.5", "10.0.0.6"],
            "ReportedFromIP": "203.0.113.9"
        });
        assert_eq!(extract_ip_address(&value).as_deref(), Some("10.0.0.5"));
    }

    #[test]
    fn extract_ip_address_skips_empty_strings_in_ip_addresses_array() {
        let value = serde_json::json!({
            "IpAddresses": ["", "10.0.0.9"],
            "ReportedFromIP": "203.0.113.9"
        });
        assert_eq!(extract_ip_address(&value).as_deref(), Some("10.0.0.9"));
    }

    #[test]
    fn extract_ip_address_falls_back_to_reported_from_ip_when_ip_addresses_empty() {
        let value = serde_json::json!({"IpAddresses": [], "ReportedFromIP": "203.0.113.9"});
        assert_eq!(extract_ip_address(&value).as_deref(), Some("203.0.113.9"));
    }

    #[test]
    fn extract_ip_address_falls_back_to_reported_from_ip_when_ip_addresses_missing() {
        let value = serde_json::json!({"ReportedFromIP": "203.0.113.9"});
        assert_eq!(extract_ip_address(&value).as_deref(), Some("203.0.113.9"));
    }

    #[test]
    fn extract_ip_address_is_none_when_neither_field_usable() {
        let value = serde_json::json!({"IpAddresses": [], "ReportedFromIP": ""});
        assert_eq!(extract_ip_address(&value), None);
    }

    #[test]
    fn maps_401_status_to_authentication_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(401));
        assert!(matches!(err, PluginError::Authentication(_)));
    }

    #[test]
    fn maps_403_status_to_authentication_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(403));
        assert!(matches!(err, PluginError::Authentication(_)));
    }

    #[test]
    fn maps_other_status_codes_to_unreachable_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(500));
        assert!(matches!(err, PluginError::Unreachable(_)));
    }

    #[test]
    fn plugin_id_returns_configured_connection_id() {
        let plugin = AteraPlugin::new("atera:acme-123".to_string());
        assert_eq!(plugin.id(), "atera:acme-123");
    }
}
