//! Real plugin implementation for netcup (German hosting provider,
//! vServer/Root-Server VPS products) via its "Server Control Panel" (SCP)
//! REST/JSON API, see `docs/PLUGIN_ARCHITECTURE.md` section
//! "netcup-Plugin". Structurally closest to `plugin::level`: no
//! organization/tenant concept at all (verified: no "list users" endpoint,
//! no account-scoping parameter on `/servers`), so a netcup "connection"
//! (one API token) maps 1:1 to exactly one local customer
//! (`NetcupConnectionMeta.customer_id`), exactly like
//! `LevelConnectionMeta.customer_id`; there is no mapping table like
//! `plugin::tacticalrmm::TacticalRmmClientMapping`. This plugin's purpose is
//! server inventory only. netcup's SCP API has no device-management-agent
//! concept and no backup-status concept, making it the simplest kind of
//! plugin in this codebase.
//!
//! Every fact below is verified against netcup's own live OpenAPI spec
//! (<https://www.netcup.com/en/helpcenter/documentation/servercontrolpanel/api>)
//! and live, unauthenticated probe requests against the real API host. This
//! is genuinely the newer REST/JSON Server Control Panel API, NOT the older
//! SOAP-style API some netcup documentation elsewhere still describes.
//!
//! - **Authentication**: a static Bearer token, header `Authorization:
//!   Bearer <token>`. Confirmed live: an unauthenticated request returns
//!   `401` with `{"message":"Authorization header missing."}`, a malformed
//!   header names the exact required format, and a well-formed-but-fake
//!   token returns `{"message":"Invalid token."}` (definitively JSON/Bearer,
//!   not the SOAP/XML-RPC shape some netcup docs elsewhere describe). The
//!   token itself is generated by the user inside a logged-in netcup SCP
//!   session (an "API" menu item): an out-of-band, one-time setup step the
//!   user does themselves, exactly like every other plugin's credential
//!   setup in this codebase.
//! - **Base URL**: a single, fixed constant (`BASE_URL` below), confirmed
//!   live (`GET /scp-core/api/ping` returns `200 OK` with body `"OK"`, a
//!   public unauthenticated health check, not used by this module since
//!   `test_credentials` already exercises the real authenticated `/servers`
//!   call). Like `plugin::level::BASE_URL`, no user-supplied `base_url`
//!   field is needed on `NetcupConnectionMeta`.
//! - **Tenancy**: confirmed 1:1. No reseller/sub-account switching exists
//!   in this API at all (no "list users" endpoint, no account-scoping query
//!   parameter on `/servers`).
//! - **Servers list (minimal: no status, no IP)**: `GET {BASE_URL}/servers`,
//!   query params `limit`/`offset` (both integers; `name`/`ip`/`q`/`sort`
//!   also exist but aren't needed here). Response is a **bare JSON array**
//!   (verified, NOT wrapped in an envelope key like Hetzner's
//!   `{"servers": [...]}`), items shaped `{"id": <int32>, "name":
//!   "<string, e.g. v123456>", "hostname": "<string or null>", "nickname":
//!   "<string or null>", "disabled": <bool>, "template": {...} | null}`.
//!   `id` (stringified) becomes `external_id`; the display name prefers
//!   `nickname`, then `hostname`, then finally the raw netcup `name`
//!   (`vXXXXX`-style identifier) as a last resort, the same "prefer the
//!   human label, fall back to the raw identifier" convention
//!   `plugin::tacticalrmm`'s hostname then agent_id fallback already
//!   established here. **This list endpoint has genuinely no status field
//!   and no IP address field at all.** See `NetcupServer`'s own doc comment
//!   on why this type deliberately has no `status`/`ip_address` fields,
//!   rather than always-`None` ones that would misleadingly imply the list
//!   call at least tried.
//! - **Pagination**: `limit`/`offset` exist, but the response carries no
//!   total-count field and no documented default/max page size, so
//!   `fetch_all_servers` uses the standard defensive heuristic for that
//!   shape of API: keep incrementing `offset` by a fixed `PAGE_LIMIT` while
//!   the just-fetched page's length equals `PAGE_LIMIT`, stop as soon as a
//!   page returns fewer items (see `page_indicates_more`, a small pure
//!   function so this decision is unit-testable without real network
//!   access). `MAX_PAGES` caps the whole walk, the same defensive brake
//!   `plugin::level::MAX_PAGES` uses against a pathological remote end.
//! - **Single-server detail (rich: real status and IP)**: `GET
//!   {BASE_URL}/servers/{serverId}` (`serverId` = the same integer `id`),
//!   `loadServerLiveInfo` left unset (defaults to `true`, so the live state
//!   is included). Response carries `serverLiveInfo.state` (a free-form
//!   libvirt-domain-state string, e.g. `RUNNING`/`SHUTOFF`/`CRASHED`; no
//!   Rust enum, so a future netcup-added state value doesn't break
//!   parsing), `ipv4Addresses` (an array of `{id, ip, netmask, gateway,
//!   broadcast}`, the first entry's `ip` is the natural display value),
//!   `ipv6Addresses` (an array of `{id, networkPrefix,
//!   networkPrefixLength, gateway}`, deliberately NOT used for any display
//!   IP: unlike `ipv4Addresses`, these are prefix/gateway pairs, not host
//!   addresses, so there is no honest single "the IPv6" to extract),
//!   `site.city`/`architecture` (informational display strings).
//!   `Plugin::get_system_details` passes this response through unmodified
//!   as `serde_json::Value`, the same "caller/UI interprets it" contract
//!   every other plugin's `get_system_details` uses, and is deliberately
//!   the ONLY place this module ever calls the detail endpoint:
//!   `list_servers`/`list_systems`/`sync_netcup_connection` never call it
//!   once per server during a sync run, which would be an N+1 pattern
//!   against an undocumented rate limit.
//! - **Rate limits**: only explicitly documented for an unrelated
//!   failover-IP-routing endpoint (10 req/5min, 20 req/60min). Nothing is
//!   documented for `/servers` or the detail endpoint used here, so no
//!   special retry/backoff logic is implemented.
//! - **Web dashboard deep-link**: NOT verifiable. A guessed SCP route
//!   returned a genuine `404` against the real host, so it is deliberately
//!   left out entirely, the same honest omission principle as
//!   `plugin::tacticalrmm`'s missing dashboard link.
//! - **HTTP client**: `ureq`, synchronous, the same dependency every other
//!   plugin module here uses.
//! - **Credential encoding**: netcup needs only a single secret value (the
//!   Bearer token), passed through 1:1 as `PluginCredentials.secret`, like
//!   Level.io/Tactical RMM: no JSON encoding of multiple values.

use std::time::Duration;

use serde::{Deserialize, Serialize};
use ureq::Agent;

use super::{ExternalSystem, Plugin, PluginCredentials, PluginError};

/// Fixed constant: netcup's Server Control Panel API has no region or
/// instance variants (verified), hence no user-supplied `base_url` field on
/// `NetcupConnectionMeta`, exactly like `plugin::level::BASE_URL`. All real
/// endpoints live under `/scp-core/api/v1/...` (verified, see module docs).
pub const BASE_URL: &str = "https://www.servercontrolpanel.de/scp-core/api/v1";

/// Protection against a misbehaving remote end (an endless run of
/// full-length pages): more than `MAX_PAGES * PAGE_LIMIT` servers per sync
/// run are not fetched. Netcup's `/servers` response documents no
/// total-count field and no default/max page size (see module docs), so
/// this defensive cap exists for the same reason `plugin::level::MAX_PAGES`
/// does.
const MAX_PAGES: usize = 20;
const PAGE_LIMIT: u32 = 100;

/// Non-secret metadata of a netcup connection, as stored in `config.toml`
/// (`Config::netcup_connections`). The API token belongs, per the
/// credential principle, exclusively in the OS keyring, never here. Like
/// `LevelConnectionMeta` (and unlike `TacticalRmmConnectionMeta`), a
/// connection directly carries its `customer_id`: netcup has no
/// organization or sub-account concept, see module docs, "Tenancy".
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NetcupConnectionMeta {
    pub id: String,
    pub customer_id: i64,
    pub label: String,
}

/// A server from `GET {BASE_URL}/servers` (the minimal list endpoint, see
/// module docs). Deliberately only `external_id`/`name`: netcup's list
/// endpoint genuinely has no status field and no IP address field at all
/// (verified live, see module docs, "Servers list"). Adding always-`None`
/// `status`/`ip_address` fields directly on THIS type would misleadingly
/// suggest the list call at least tried and simply found nothing, the same
/// "verified gap" honesty `plugin::pulseway::PulsewayDevice` already
/// established for its own permanently unavailable fields. Unlike
/// Pulseway, netcup's status and IP genuinely exist, just never from this
/// call: only via `Plugin::get_system_details` (the per-server detail
/// call), which is why `commands::netcup::ExternalSystemDto` (the type
/// that actually reaches the cache file and the frontend) DOES carry
/// `status`/`ip_address` fields, clearly documented there as always `None`
/// when built from a `NetcupServer`. See that module's doc comment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct NetcupServer {
    pub external_id: String,
    pub name: String,
    /// netcup's own provisioning-image/template name (e.g. `"Debian 12"`),
    /// read from the nested `template.name` field verified present on the
    /// same `GET /scp-core/api/v1/servers` response `map_server` already
    /// parses. Best-effort only, unlike the other plugins in this batch:
    /// `template` is `null` whenever a server was never (re)installed
    /// through netcup's own panel (e.g. a manual OS reinstall bypassing
    /// netcup's provisioning flow), so a `None` here does not necessarily
    /// mean "no OS", just "netcup doesn't know".
    pub operating_system: Option<String>,
}

/// A plugin object for exactly one configured netcup connection. `id` here
/// is already the fully qualified identifier (`"netcup:<connection_id>"`),
/// so that `Plugin::id()` works unmodified as the `plugin_id`/keyring
/// account (see trait documentation in `plugin::mod`). Like `LevelPlugin`,
/// this type needs no `base_url` field (see `BASE_URL` above) and no
/// cached token: the API token comes fresh from `PluginCredentials` on
/// every call.
pub struct NetcupPlugin {
    id: String,
}

impl NetcupPlugin {
    pub fn new(id: String) -> Self {
        Self { id }
    }

    /// Live fetch of ALL servers of this connection, with pagination walked
    /// internally (see module docs, "Pagination"). Richer-named than the
    /// trait method `list_systems` only in intent: `NetcupServer` and
    /// `ExternalSystem` happen to carry the same two fields today, but this
    /// inherent method is the one `commands::netcup::sync_netcup_connection`
    /// calls, exactly mirroring `LevelPlugin::list_devices`.
    pub fn list_servers(
        &self,
        credentials: &PluginCredentials,
    ) -> Result<Vec<NetcupServer>, PluginError> {
        let agent = build_agent();
        let raw_servers = fetch_all_servers(&agent, &credentials.secret)?;
        Ok(map_servers(&raw_servers))
    }
}

/// Checks an API token against netcup (a lightweight, real call:
/// `GET /servers?limit=1`), without persisting anything. For
/// `commands::netcup::test_netcup_connection`, so users notice a typo in
/// the API token before actually creating a connection (writing
/// credentials to the keyring), exactly the same pattern as
/// `plugin::level::test_credentials`.
pub fn test_credentials(api_token: &str) -> Result<(), PluginError> {
    let agent = build_agent();
    fetch_servers_page(&agent, api_token, 0, 1)?;
    Ok(())
}

impl Plugin for NetcupPlugin {
    fn id(&self) -> &str {
        self.id.as_str()
    }

    fn list_systems(
        &self,
        credentials: &PluginCredentials,
    ) -> Result<Vec<ExternalSystem>, PluginError> {
        let servers = self.list_servers(credentials)?;
        Ok(servers
            .into_iter()
            .map(|s| ExternalSystem {
                external_id: s.external_id,
                name: s.name,
                // netcup's list endpoint has no separate hostname field
                // worth surfacing here. The nickname/hostname/name fallback
                // already happened server-side into `name` (see
                // `map_server`), matching `NetcupServer`'s own deliberately
                // narrow shape (see its doc comment).
                hostname: None,
            })
            .collect())
    }

    fn get_system_details(
        &self,
        credentials: &PluginCredentials,
        external_id: &str,
    ) -> Result<serde_json::Value, PluginError> {
        let agent = build_agent();
        fetch_server_detail_json(&agent, &credentials.secret, external_id)
    }

    fn link_system(&self, local_system_id: i64, external_id: &str) -> Result<(), PluginError> {
        // netcup's API doesn't need to know anything about a local link,
        // purely a local bookkeeping concept (see trait documentation).
        // Persisted by the caller via `db::external_refs::upsert`.
        println!("NetcupPlugin({}): verknüpfe lokales System {local_system_id} mit externer ID {external_id}", self.id);
        Ok(())
    }
}

fn build_agent() -> Agent {
    let config = Agent::config_builder()
        .timeout_global(Some(Duration::from_secs(20)))
        .build();
    Agent::new_with_config(config)
}

/// Fetches all pages of `GET /servers` and returns the raw server objects
/// (not yet mapped to `NetcupServer`) as a single, merged list. Walks pages
/// via `offset`/`limit` (see module docs, "Pagination"), stopping as soon as
/// a page's length is shorter than `PAGE_LIMIT` (`page_indicates_more`) or
/// `MAX_PAGES` is reached, whichever comes first.
fn fetch_all_servers(
    agent: &Agent,
    api_token: &str,
) -> Result<Vec<serde_json::Value>, PluginError> {
    let mut all = Vec::new();
    let mut offset: u32 = 0;
    for _ in 0..MAX_PAGES {
        let page_json = fetch_servers_page(agent, api_token, offset, PAGE_LIMIT)?;
        let page = parse_servers_page(&page_json)?;
        let page_len = page.len();
        all.extend(page);
        if !page_indicates_more(page_len, PAGE_LIMIT) {
            break;
        }
        offset += PAGE_LIMIT;
    }
    Ok(all)
}

/// The pure decision behind `fetch_all_servers`'s pagination loop (see
/// module docs, "Pagination"): only keep going while the just-fetched
/// page's length equals `limit`, the standard defensive heuristic for an
/// API with no total-count field and no explicit "has more" signal.
/// Extracted as its own function so this logic is unit-testable without
/// real network access.
fn page_indicates_more(page_len: usize, limit: u32) -> bool {
    page_len as u64 == limit as u64
}

fn fetch_servers_page(
    agent: &Agent,
    api_token: &str,
    offset: u32,
    limit: u32,
) -> Result<serde_json::Value, PluginError> {
    let url = format!("{BASE_URL}/servers");
    let mut response = agent
        .get(&url)
        .header("Authorization", format!("Bearer {api_token}"))
        .query("limit", limit.to_string())
        .query("offset", offset.to_string())
        .call()
        .map_err(map_ureq_error)?;
    response
        .body_mut()
        .read_json::<serde_json::Value>()
        .map_err(map_ureq_error)
}

fn fetch_server_detail_json(
    agent: &Agent,
    api_token: &str,
    external_id: &str,
) -> Result<serde_json::Value, PluginError> {
    let url = format!("{BASE_URL}/servers/{external_id}");
    let mut response = agent
        .get(&url)
        .header("Authorization", format!("Bearer {api_token}"))
        .call()
        .map_err(map_ureq_error)?;
    response
        .body_mut()
        .read_json::<serde_json::Value>()
        .map_err(map_ureq_error)
}

fn map_ureq_error(e: ureq::Error) -> PluginError {
    match e {
        ureq::Error::StatusCode(code) if code == 401 || code == 403 => {
            PluginError::Authentication(format!("netcup-API antwortete mit Status {code}"))
        }
        ureq::Error::StatusCode(code) => {
            PluginError::Unreachable(format!("netcup-API antwortete mit Status {code}"))
        }
        ureq::Error::Json(err) => {
            PluginError::UnexpectedResponse(format!("Ungültige JSON-Antwort: {err}"))
        }
        other => PluginError::Unreachable(other.to_string()),
    }
}

/// Extracts the server list from a single `GET /servers` page response: a
/// **bare JSON array** (verified, see module docs; unlike Hetzner's
/// `{"servers": [...]}` envelope). Pure function, testable with hardcoded
/// JSON, no real network access needed.
fn parse_servers_page(json: &serde_json::Value) -> Result<Vec<serde_json::Value>, PluginError> {
    json.as_array().cloned().ok_or_else(|| {
        PluginError::UnexpectedResponse("Erwartete JSON-Liste von Servern".to_string())
    })
}

/// Maps an (already merged across all pages) list of raw netcup server
/// objects to `NetcupServer` values. Pure function, testable with
/// hardcoded JSON, netcup's "List Servers" endpoint's own item shape (see
/// module docs).
fn map_servers(servers: &[serde_json::Value]) -> Vec<NetcupServer> {
    servers.iter().filter_map(map_server).collect()
}

/// A single server object from netcup's `/servers` response (`{"id":
/// <int32>, "name": "...", "hostname": "... or null", "nickname":
/// "... or null", ...}`, verified, see module docs). A server without a
/// usable numeric `id` is skipped instead of failing the whole call: a
/// single broken server object shouldn't make the whole list unusable,
/// analogous to `plugin::level::map_level_device`'s "skip without id" rule.
/// Display name: `nickname` wins if present, then `hostname`, then finally
/// the raw netcup `name` (the `vXXXXX`-style identifier) as the last
/// resort, a verified convention (see module docs).
fn map_server(value: &serde_json::Value) -> Option<NetcupServer> {
    let id = value["id"].as_i64()?;
    let external_id = id.to_string();
    let name = value["nickname"]
        .as_str()
        .or_else(|| value["hostname"].as_str())
        .or_else(|| value["name"].as_str())
        .map(str::to_string)
        .unwrap_or_else(|| external_id.clone());
    let operating_system = value["template"]["name"].as_str().map(str::to_string);
    Some(NetcupServer {
        external_id,
        name,
        operating_system,
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_servers_page_bare_json_array() {
        let json = serde_json::json!([{"id": 1, "name": "v111"}, {"id": 2, "name": "v222"}]);
        let servers = parse_servers_page(&json).unwrap();
        assert_eq!(servers.len(), 2);
    }

    #[test]
    fn parse_servers_page_rejects_non_array_json() {
        let json = serde_json::json!({"servers": []});
        let result = parse_servers_page(&json);
        assert!(matches!(result, Err(PluginError::UnexpectedResponse(_))));
    }

    #[test]
    fn parses_empty_servers_page() {
        let json = serde_json::json!([]);
        let servers = parse_servers_page(&json).unwrap();
        assert!(servers.is_empty());
    }

    #[test]
    fn maps_servers_json_array_into_netcup_servers() {
        let json: serde_json::Value = serde_json::from_str(
            r#"[
                {"id": 111, "name": "v111", "hostname": "srv-01.customer.local", "nickname": "Server 01", "disabled": false, "template": null},
                {"id": 222, "name": "v222", "hostname": "fw-edge", "nickname": null, "disabled": false, "template": null}
            ]"#,
        )
        .unwrap();
        let servers = map_servers(json.as_array().unwrap());

        assert_eq!(servers.len(), 2);
        assert_eq!(servers[0].external_id, "111");
        assert_eq!(servers[0].name, "Server 01");
        // Neither sample object carries a "template" key at all -> None,
        // not an error.
        assert_eq!(servers[0].operating_system, None);
        assert_eq!(servers[1].external_id, "222");
        assert_eq!(servers[1].name, "fw-edge");
        assert_eq!(servers[1].operating_system, None);
    }

    #[test]
    fn maps_operating_system_from_nested_template_name() {
        let json = serde_json::json!([
            {"id": 333, "name": "v333", "template": {"id": 7, "name": "Debian 12"}}
        ]);
        let servers = map_servers(json.as_array().unwrap());
        assert_eq!(servers[0].operating_system.as_deref(), Some("Debian 12"));
    }

    #[test]
    fn skips_servers_without_a_usable_numeric_id() {
        let json = serde_json::json!([{"name": "v111", "hostname": "ohne-id"}]);
        let servers = map_servers(json.as_array().unwrap());
        assert!(servers.is_empty());
    }

    #[test]
    fn display_name_prefers_nickname_when_present() {
        let json = serde_json::json!([{
            "id": 1, "name": "v001", "hostname": "host-1", "nickname": "Mein Server"
        }]);
        let servers = map_servers(json.as_array().unwrap());
        assert_eq!(servers[0].name, "Mein Server");
    }

    #[test]
    fn display_name_falls_back_to_hostname_when_nickname_is_null() {
        let json = serde_json::json!([{
            "id": 1, "name": "v001", "hostname": "host-1", "nickname": null
        }]);
        let servers = map_servers(json.as_array().unwrap());
        assert_eq!(servers[0].name, "host-1");
    }

    #[test]
    fn display_name_falls_back_to_hostname_when_nickname_missing() {
        let json = serde_json::json!([{"id": 1, "name": "v001", "hostname": "host-1"}]);
        let servers = map_servers(json.as_array().unwrap());
        assert_eq!(servers[0].name, "host-1");
    }

    #[test]
    fn display_name_falls_back_to_raw_name_when_nickname_and_hostname_absent() {
        let json = serde_json::json!([{"id": 1, "name": "v001"}]);
        let servers = map_servers(json.as_array().unwrap());
        assert_eq!(servers[0].name, "v001");
    }

    #[test]
    fn display_name_falls_back_to_raw_name_when_nickname_and_hostname_are_null() {
        let json =
            serde_json::json!([{"id": 1, "name": "v001", "hostname": null, "nickname": null}]);
        let servers = map_servers(json.as_array().unwrap());
        assert_eq!(servers[0].name, "v001");
    }

    #[test]
    fn display_name_falls_back_to_external_id_when_no_name_field_at_all() {
        let json = serde_json::json!([{"id": 1}]);
        let servers = map_servers(json.as_array().unwrap());
        assert_eq!(servers[0].name, "1");
    }

    #[test]
    fn page_indicates_more_when_page_is_exactly_full() {
        assert!(page_indicates_more(100, 100));
    }

    #[test]
    fn page_indicates_more_is_false_when_page_is_shorter_than_limit() {
        assert!(!page_indicates_more(37, 100));
    }

    #[test]
    fn page_indicates_more_is_false_for_an_empty_page() {
        assert!(!page_indicates_more(0, 100));
    }

    #[test]
    fn maps_401_status_to_authentication_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(401));
        assert!(matches!(err, PluginError::Authentication(_)));
    }

    #[test]
    fn maps_403_status_to_authentication_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(403));
        assert!(matches!(err, PluginError::Authentication(_)));
    }

    #[test]
    fn maps_other_status_codes_to_unreachable_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(500));
        assert!(matches!(err, PluginError::Unreachable(_)));
    }

    #[test]
    fn maps_json_decode_failure_to_unexpected_response_error() {
        let json_err = serde_json::from_str::<serde_json::Value>("not json").unwrap_err();
        let err = map_ureq_error(ureq::Error::Json(json_err));
        assert!(matches!(err, PluginError::UnexpectedResponse(_)));
    }

    #[test]
    fn plugin_id_returns_configured_connection_id() {
        let plugin = NetcupPlugin::new("netcup:acme-123".to_string());
        assert_eq!(plugin.id(), "netcup:acme-123");
    }
}
