//! Real plugin implementation for Tactical RMM (self-hosted, open-source
//! RMM, <https://github.com/amidaware/tacticalrmm>), see
//! `docs/PLUGIN_ARCHITECTURE.md` section "Tactical-RMM-Plugin". Fourth real
//! integration after NinjaOne (`plugin::ninja`), Level.io (`plugin::level`)
//! and Snipe-IT (`plugin::snipeit`). Structurally closest to NinjaOne:
//! self-hosted (a user-supplied `base_url`, like NinjaOne/Snipe-IT, unlike
//! Level.io's fixed constant) with a genuine multi-tenant hierarchy within a
//! single connection (Tactical RMM's "Client" -> "Site" -> "Agent",
//! conceptually the same shape as NinjaOne's "Organization" -> "Device") --
//! hence the same connection+mapping-table pattern as NinjaOne
//! (`TacticalRmmConnectionMeta`/`TacticalRmmClientMapping`, mapping
//! granularity at the Client level, NOT Site -- a Client can have multiple
//! Sites, but this integration deliberately doesn't add a second mapping
//! layer for those, mirroring how NinjaOne maps at the Organization level
//! and not some finer subdivision). Authentication, however, is a single
//! static secret like Level.io/Snipe-IT (no OAuth2 grant like NinjaOne).
//!
//! Every fact below is verified directly against Tactical RMM's own backend
//! source on GitHub (`amidaware/tacticalrmm`, `master` branch,
//! `api/tacticalrmm/`), not guessed from documentation prose:
//!
//! - **Authentication**: a static API key in a custom `X-API-KEY` header
//!   (NOT `Authorization: Bearer`), verified via
//!   `tacticalrmm/auth.py::APIAuthentication`/`get_authorization_header`
//!   (`request.META.get("HTTP_X_API_KEY", ...)`). Generated by the user in
//!   Tactical RMM's own web UI (Settings -> Global Settings -> API Keys). No
//!   token exchange, no OAuth2 grant -- like Level.io/Snipe-IT, just a
//!   different header name and no `Bearer ` prefix.
//! - **Self-hosted**: like NinjaOne/Snipe-IT (and unlike Level.io's fixed
//!   `BASE_URL` constant), a connection needs a base URL supplied by the
//!   user (`TacticalRmmConnectionMeta.base_url`). Tactical RMM's REST API
//!   has no fixed path prefix -- verified via `tacticalrmm/urls.py`:
//!   `path("clients/", include("clients.urls"))`/
//!   `path("agents/", include("agents.urls"))` sit directly under the API
//!   root, unlike Snipe-IT's fixed `/api/v1` suffix.
//! - **Clients (multi-tenancy)**: `GET {base_url}/clients/`, verified via
//!   `clients/views.py::GetAddClients.get`
//!   (`return Response(ClientSerializer(clients, many=True).data)`) -- a
//!   bare, UNPAGINATED JSON array (not Snipe-IT's `{"total", "rows"}`
//!   envelope, not a cursor like Level.io), each client shaped per
//!   `clients/serializers.py::ClientSerializer`: `{"id": <number>, "name":
//!   "...", "sites": [...], ...}`. `sites` is a nested array (each site
//!   object itself has its own `"id"`/`"name"`) -- deliberately not read
//!   here, see the "Client > Site > Agent" note above: this plugin only
//!   reads `id`/`name` off the top-level client object, mapping granularity
//!   stays at the Client level.
//! - **Agents**: `GET {base_url}/agents/?detail=true` (the DEFAULT when the
//!   `detail` query parameter is omitted entirely, sent explicitly here
//!   anyway for clarity/future-proofing). IMPORTANT, a genuine correction to
//!   an initial assumption made before checking the real source:
//!   `detail=false` is NOT the richer listing -- verified via
//!   `agents/views.py::GetAgents.get`, the branch for "`detail` absent OR
//!   `detail=true`" uses `AgentTableSerializer` (rich: hostname, client
//!   name, site name, status, platform, IP...); the `detail=false` branch
//!   uses the much leaner `AgentHostnameSerializer` (`id`, `hostname`,
//!   `agent_id`, `client`, `site` -- just names, no status/platform/IP).
//!   This plugin therefore explicitly requests `detail=true` -- the exact
//!   opposite query value an initial, unverified reading of the brief would
//!   have suggested. Also a bare, unpaginated JSON array, same as
//!   `/clients/`.
//! - **No numeric client/site ID on an agent, in EITHER agent serializer
//!   variant**: verified against `agents/serializers.py` --
//!   `AgentTableSerializer.Meta.fields` has `"client_name"`
//!   (`ReadOnlyField(source="site.client.name")`) and `"site_name"`
//!   (`ReadOnlyField(source="site.name")`) as flat display strings, nothing
//!   else referencing the parent Client/Site; `AgentHostnameSerializer` is
//!   the same story with `"client"`/`"site"` (also name strings, via
//!   `source="client.name"`/`source="site.name"`). This is a genuine,
//!   verified deviation from NinjaOne (`organizationId`, a real numeric
//!   foreign key on the device): grouping an agent under its Client can only
//!   be done by matching `agent.client_name` against `client.name` (a
//!   STRING join), not by ID. `map_agents_response` here, and
//!   `commands::tacticalrmm::group_agents_by_client`, are written around
//!   this verified reality, not an assumed ID-based shape.
//!   `TacticalRmmClientMapping.client_id` itself IS still the real numeric
//!   Client ID (from `/clients/`, where an ID genuinely exists) -- only the
//!   per-agent join needs the name-based workaround.
//! - **Agent identifier**: `agent_id`, a unique string (verified via
//!   `agents/models.py`: `agent_id = models.CharField(max_length=200,
//!   unique=True)`), used as the URL path segment for a single agent
//!   (`GET {base_url}/agents/{agent_id}/`, verified via `agents/urls.py`:
//!   `path("<agent:agent_id>/", views.GetUpdateDeleteAgent.as_view())`). The
//!   Django-internal numeric `id` primary key is deliberately excluded from
//!   `AgentTableSerializer` entirely -- `agent_id` is the only identifier
//!   this plugin ever sees or uses, exactly like `ExternalSystem::external_id`
//!   here always holds `agent_id`, never a numeric ID.
//! - **IP address**: `public_ip` is a single string field (verified via
//!   `agents/models.py`); `local_ips` is a computed, comma-separated STRING
//!   property (verified: `", ".join(...)` for POSIX agents, a manually
//!   built comma-joined list for Windows agents), NOT an array like
//!   NinjaOne's `ipAddresses` -- and can also hold the literal error string
//!   `"error getting local ips"` on the agent's own side (verified in the
//!   same model property). `extract_ip_address` takes the first
//!   comma-separated token of `local_ips` if it looks like a real value
//!   (non-empty, doesn't contain "error"), else falls back to `public_ip`.
//! - **Status/platform**: `status` is one of the verified string constants
//!   `"online"`/`"offline"`/`"overdue"` (`tacticalrmm/constants.py`:
//!   `AGENT_STATUS_ONLINE`/`AGENT_STATUS_OFFLINE`/`AGENT_STATUS_OVERDUE`);
//!   `plat` is one of `"windows"`/`"linux"`/`"darwin"` (`AgentPlat` text
//!   choices in the same file). Both are passed through here as free-form
//!   strings -- no Rust enum -- so a future Tactical RMM release adding a
//!   new value doesn't break parsing.
//! - **No verified web UI link**: unlike NinjaOne/Snipe-IT, Tactical RMM's
//!   web dashboard (a separate Vue SPA, `amidaware/tacticalrmm-web`) is
//!   commonly deployed on its OWN subdomain/host, independent of the API's
//!   `base_url` -- a well-documented Tactical RMM deployment convention
//!   (typically an `api.` host for the backend and a separate `rmm.`/root
//!   host for the dashboard). Unlike NinjaOne's `ninja_url`/Snipe-IT's
//!   `snipeit_url` (both verifiably derivable from `base_url`, because those
//!   tools serve API and web UI from the SAME host), there is no honest way
//!   to construct a dashboard link from `base_url` alone here -- so this
//!   integration deliberately has NO `tacticalrmm_url` field/DTO property.
//!   An honest omission, analogous to Snipe-IT's verified `hostname`/
//!   `ip_address` always `None` (see `plugin::snipeit` module
//!   documentation), not a guess dressed up as a feature.
//! - **HTTP client**: `ureq` 3.4.1, synchronous, the same dependency as
//!   `plugin::ninja`/`plugin::level`/`plugin::snipeit`.
//! - **Credential encoding**: Tactical RMM needs only a single secret value
//!   (the API key), passed through 1:1 as `PluginCredentials.secret` --
//!   like Level.io/Snipe-IT, no JSON encoding of multiple values is needed
//!   (unlike NinjaOne).

use serde::{Deserialize, Serialize};
use std::time::Duration;
use ureq::Agent;

use super::{ExternalSystem, Plugin, PluginCredentials, PluginError};

/// Non-secret metadata of a Tactical RMM connection, as stored in
/// `config.toml` (`Config::tacticalrmm_connections`). The API key belongs,
/// per the credential principle, exclusively in the OS keyring, never here.
/// Deliberately WITHOUT `customer_id` -- a connection is a Tactical RMM
/// instance, not a local customer; which Tactical RMM "Client" within this
/// instance corresponds to which local customer is tracked granularly in
/// `TacticalRmmClientMapping`/`Config::tacticalrmm_client_mappings` --
/// exactly the same principle as `plugin::ninja::NinjaConnectionMeta`/
/// `plugin::snipeit::SnipeitConnectionMeta`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TacticalRmmConnectionMeta {
    pub id: String,
    pub label: String,
    pub base_url: String,
}

/// Mapping of a single Tactical RMM "Client" (within a connection) to a
/// local customer. Lives in `Config::tacticalrmm_client_mappings`, not in
/// `TacticalRmmConnectionMeta` -- a connection can see multiple clients,
/// each of which can be mapped independently (or left unmapped). `client_id`
/// is the real, numeric Tactical RMM client ID (as a string, from
/// `GET /clients/`); `client_name` is stored alongside it so a UI list can
/// display a readable name without another live call against Tactical RMM
/// -- analogous to `plugin::ninja::NinjaOrgMapping`/
/// `plugin::snipeit::SnipeitCompanyMapping`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TacticalRmmClientMapping {
    pub connection_id: String,
    pub client_id: String,
    pub client_name: String,
    pub customer_id: i64,
}

/// A client reported by `GET /clients/`. Separate from `ExternalSystem`
/// (those are agents) -- its own, small shape type, analogous to
/// `plugin::ninja::NinjaOrganization`/`plugin::snipeit::SnipeitCompany`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TacticalRmmClient {
    pub id: String,
    pub name: String,
}

/// A single agent from `GET /agents/?detail=true`, enriched with the
/// verified extra fields `plugin::mod::ExternalSystem` deliberately does not
/// provide (status, platform, site name, and the flat `client_name` used for
/// grouping -- see the module documentation on why this is a NAME rather
/// than an ID). Needed by `commands::tacticalrmm::sync_tacticalrmm_connection`
/// for grouping by client and for display, analogous to
/// `plugin::ninja::NinjaDevice`/`plugin::snipeit::SnipeitDevice`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TacticalRmmAgent {
    pub external_id: String,
    pub name: String,
    pub hostname: Option<String>,
    pub ip_address: Option<String>,
    /// One of `"online"`/`"offline"`/`"overdue"` per Tactical RMM's own
    /// verified constants -- kept as a free-form string, not an enum, so a
    /// future additional value doesn't break parsing (see module docs).
    pub status: Option<String>,
    /// One of `"windows"`/`"linux"`/`"darwin"` per Tactical RMM's own
    /// verified `AgentPlat` choices -- same free-form-string rationale as
    /// `status`.
    pub platform: Option<String>,
    /// The agent's owning client, as a NAME (verified: Tactical RMM's agent
    /// list serializers carry no numeric client ID at all, see module
    /// docs) -- used as the join key in
    /// `commands::tacticalrmm::group_agents_by_client`.
    pub client_name: String,
    pub site_name: Option<String>,
}

/// A plugin object for exactly one configured Tactical RMM connection. `id`
/// here is already the fully qualified identifier
/// (`"tacticalrmm:<connection_id>"`), so that `Plugin::id()` works
/// unmodified as the `plugin_id`/keyring account (see trait documentation in
/// `plugin::mod`).
pub struct TacticalRmmPlugin {
    id: String,
    base_url: String,
}

impl TacticalRmmPlugin {
    pub fn new(id: String, base_url: String) -> Self {
        Self { id, base_url }
    }

    /// Live fetch of this connection's client list (`GET /clients/`).
    /// Separate from the `Plugin` trait method `list_systems`, because
    /// clients are not agents and the generic trait has no room for that --
    /// analogous to `plugin::ninja::NinjaPlugin::list_organizations`/
    /// `plugin::snipeit::SnipeitPlugin::list_companies`.
    pub fn list_clients(
        &self,
        credentials: &PluginCredentials,
    ) -> Result<Vec<TacticalRmmClient>, PluginError> {
        let agent = build_agent();
        let json = fetch_json(&agent, &self.base_url, "/clients/", &credentials.secret)?;
        map_clients_response(&json)
    }

    /// Live fetch of all this connection's agents (`GET /agents/?detail=true`,
    /// see module docs on why `detail=true`, not `detail=false`). Richer
    /// than the trait method `list_systems`, which deliberately stays with
    /// the narrow, plugin-agnostic `ExternalSystem` type (no `status`/
    /// `platform`/`client_name`/`site_name` field there).
    pub fn list_agents(
        &self,
        credentials: &PluginCredentials,
    ) -> Result<Vec<TacticalRmmAgent>, PluginError> {
        let agent = build_agent();
        let json = fetch_agents_json(&agent, &self.base_url, &credentials.secret)?;
        map_agents_response(&json)
    }
}

/// Checks an API key against Tactical RMM (a lightweight, real call:
/// `GET /clients/`, unpaginated so this never fetches more than the actual
/// client list), without persisting anything. For
/// `commands::tacticalrmm::test_tacticalrmm_connection`, so users notice a
/// typo in the base URL/API key before actually creating a connection
/// (writing credentials to the keyring) -- exactly the same pattern as
/// `plugin::level::test_credentials`/`plugin::snipeit::test_credentials`.
pub fn test_credentials(base_url: &str, api_key: &str) -> Result<(), PluginError> {
    let agent = build_agent();
    fetch_json(&agent, base_url, "/clients/", api_key)?;
    Ok(())
}

impl Plugin for TacticalRmmPlugin {
    fn id(&self) -> &str {
        self.id.as_str()
    }

    fn list_systems(
        &self,
        credentials: &PluginCredentials,
    ) -> Result<Vec<ExternalSystem>, PluginError> {
        let agents = self.list_agents(credentials)?;
        Ok(agents
            .into_iter()
            .map(|a| ExternalSystem {
                external_id: a.external_id,
                name: a.name,
                hostname: a.hostname,
            })
            .collect())
    }

    fn get_system_details(
        &self,
        credentials: &PluginCredentials,
        external_id: &str,
    ) -> Result<serde_json::Value, PluginError> {
        let agent = build_agent();
        fetch_json(
            &agent,
            &self.base_url,
            &format!("/agents/{external_id}/"),
            &credentials.secret,
        )
    }

    fn link_system(&self, local_system_id: i64, external_id: &str) -> Result<(), PluginError> {
        // Tactical RMM's API doesn't need to know anything about a local
        // link -- purely a local bookkeeping concept, see trait
        // documentation. Persisted by the caller via
        // `db::external_refs::upsert`.
        println!("TacticalRmmPlugin({}): verknüpfe lokales System {local_system_id} mit externer ID {external_id}", self.id);
        Ok(())
    }
}

fn build_agent() -> Agent {
    let config = Agent::config_builder()
        .timeout_global(Some(Duration::from_secs(20)))
        .build();
    Agent::new_with_config(config)
}

/// Issues an authenticated `GET {base_url}{path}` and returns the parsed
/// JSON body. Auth header is `X-API-KEY` (see module docs), NOT
/// `Authorization: Bearer` like NinjaOne/Snipe-IT.
fn fetch_json(
    agent: &Agent,
    base_url: &str,
    path: &str,
    api_key: &str,
) -> Result<serde_json::Value, PluginError> {
    let url = format!("{}{path}", base_url.trim_end_matches('/'));
    let mut response = agent
        .get(&url)
        .header("X-API-KEY", api_key)
        .call()
        .map_err(map_ureq_error)?;
    response
        .body_mut()
        .read_json::<serde_json::Value>()
        .map_err(map_ureq_error)
}

/// Same as `fetch_json`, but specifically for `GET /agents/`, always sending
/// `detail=true` explicitly (see module docs on why this, not `detail=false`,
/// is the rich listing).
fn fetch_agents_json(
    agent: &Agent,
    base_url: &str,
    api_key: &str,
) -> Result<serde_json::Value, PluginError> {
    let url = format!("{}/agents/", base_url.trim_end_matches('/'));
    let mut response = agent
        .get(&url)
        .header("X-API-KEY", api_key)
        .query("detail", "true")
        .call()
        .map_err(map_ureq_error)?;
    response
        .body_mut()
        .read_json::<serde_json::Value>()
        .map_err(map_ureq_error)
}

fn map_ureq_error(e: ureq::Error) -> PluginError {
    match e {
        ureq::Error::StatusCode(code) if code == 401 || code == 403 => {
            PluginError::Authentication(format!("Tactical-RMM-API antwortete mit Status {code}"))
        }
        ureq::Error::StatusCode(code) => {
            PluginError::Unreachable(format!("Tactical-RMM-API antwortete mit Status {code}"))
        }
        ureq::Error::Json(err) => {
            PluginError::UnexpectedResponse(format!("Ungültige JSON-Antwort: {err}"))
        }
        other => PluginError::Unreachable(other.to_string()),
    }
}

/// Maps the JSON array returned by `GET /clients/` to `TacticalRmmClient`
/// values. Deliberately extracted as its own, pure function -- can be tested
/// with a fixed JSON string, without any real network access. Requires a
/// bare JSON array (no wrapping envelope key) -- verified via
/// `clients/views.py::GetAddClients.get` (see module docs), so unlike
/// Snipe-IT's `{"total", "rows"}` envelope there is nothing to unwrap here.
fn map_clients_response(json: &serde_json::Value) -> Result<Vec<TacticalRmmClient>, PluginError> {
    let array = json.as_array().ok_or_else(|| {
        PluginError::UnexpectedResponse("Erwartete JSON-Liste von Clients".to_string())
    })?;
    Ok(array.iter().filter_map(map_client).collect())
}

/// A single client object from Tactical RMM's `/clients/` response
/// (`{"id": <number>, "name": "...", "sites": [...], ...}`, verified via
/// `clients/serializers.py::ClientSerializer`, see module docs). If `id` is
/// missing or has an unexpected shape -> the client is skipped instead of
/// failing the whole call, analogous to `plugin::ninja::map_organization`/
/// `plugin::snipeit::map_company`.
fn map_client(value: &serde_json::Value) -> Option<TacticalRmmClient> {
    let id = match &value["id"] {
        serde_json::Value::Number(n) => n.to_string(),
        serde_json::Value::String(s) => s.clone(),
        _ => return None,
    };
    let name = value["name"].as_str().unwrap_or(id.as_str()).to_string();
    Some(TacticalRmmClient { id, name })
}

/// Maps the JSON array returned by `GET /agents/?detail=true` to
/// `TacticalRmmAgent` values. Pure function, testable on its own with
/// hardcoded JSON, analogous to `map_clients_response`.
fn map_agents_response(json: &serde_json::Value) -> Result<Vec<TacticalRmmAgent>, PluginError> {
    let array = json.as_array().ok_or_else(|| {
        PluginError::UnexpectedResponse("Erwartete JSON-Liste von Agenten".to_string())
    })?;
    Ok(array.iter().filter_map(map_agent).collect())
}

/// A single agent object from Tactical RMM's `/agents/?detail=true` response
/// (`AgentTableSerializer`, verified field list: `agent_id`, `hostname`,
/// `client_name`, `site_name`, `status`, `plat`, `public_ip`, `local_ips`,
/// ... -- see module docs). An agent without a usable `agent_id` OR without
/// `client_name` is skipped -- without a client name it can't be
/// meaningfully grouped (see module docs on the name-based join), and a
/// single broken agent object shouldn't make the whole list unusable,
/// analogous to `plugin::ninja::map_ninja_device`'s "skip without
/// organizationId" rule.
fn map_agent(value: &serde_json::Value) -> Option<TacticalRmmAgent> {
    let external_id = value["agent_id"].as_str()?.to_string();
    let client_name = value["client_name"].as_str()?.to_string();
    let hostname = value["hostname"].as_str().map(str::to_string);
    let name = hostname.clone().unwrap_or_else(|| external_id.clone());
    let site_name = value["site_name"].as_str().map(str::to_string);
    let status = value["status"].as_str().map(str::to_string);
    let platform = value["plat"].as_str().map(str::to_string);
    let ip_address = extract_ip_address(value);
    Some(TacticalRmmAgent {
        external_id,
        name,
        hostname,
        ip_address,
        status,
        platform,
        client_name,
        site_name,
    })
}

/// Extracts a display IP address for an agent. `local_ips` is a
/// comma-separated STRING (verified via `agents/models.py`, see module
/// docs) that can also hold the literal error string `"error getting local
/// ips"` -- the first comma-separated token is used only if it's non-empty
/// and doesn't itself look like that error text; `public_ip` (a plain
/// string field) is the fallback, mirroring the "primary + fallback"
/// convention already used by `plugin::ninja::map_ninja_device`/
/// `plugin::level::extract_ip_address`, just adapted to Tactical RMM's
/// actually-verified string (not array) shape.
fn extract_ip_address(value: &serde_json::Value) -> Option<String> {
    let from_local_ips = value["local_ips"].as_str().and_then(|raw| {
        raw.split(',')
            .map(str::trim)
            .find(|token| !token.is_empty() && !token.to_lowercase().contains("error"))
            .map(str::to_string)
    });
    from_local_ips.or_else(|| value["public_ip"].as_str().map(str::to_string))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn maps_clients_json_array_into_tacticalrmm_clients() {
        let json: serde_json::Value = serde_json::from_str(
            r#"[
                {"id": 1, "name": "ACME GmbH", "sites": []},
                {"id": 2, "name": "Contoso AG", "sites": [{"id": 5, "name": "Hauptsitz"}]}
            ]"#,
        )
        .unwrap();

        let clients = map_clients_response(&json).unwrap();

        assert_eq!(clients.len(), 2);
        assert_eq!(
            clients[0],
            TacticalRmmClient {
                id: "1".to_string(),
                name: "ACME GmbH".to_string()
            }
        );
        assert_eq!(clients[1].id, "2");
        assert_eq!(clients[1].name, "Contoso AG");
    }

    #[test]
    fn clients_rejects_non_array_json() {
        let json = serde_json::json!({"not": "an array"});
        let result = map_clients_response(&json);
        assert!(matches!(result, Err(PluginError::UnexpectedResponse(_))));
    }

    #[test]
    fn client_falls_back_to_id_when_no_name_field_present() {
        let json = serde_json::json!([{"id": 9}]);
        let clients = map_clients_response(&json).unwrap();
        assert_eq!(clients[0].name, "9");
    }

    #[test]
    fn client_skips_entries_without_a_usable_id() {
        let json = serde_json::json!([{"name": "OhneId"}]);
        let clients = map_clients_response(&json).unwrap();
        assert!(clients.is_empty());
    }

    #[test]
    fn maps_agents_json_array_with_client_site_status_and_platform() {
        let json: serde_json::Value = serde_json::from_str(
            r#"[
                {
                    "agent_id": "abc123",
                    "hostname": "SRV-01",
                    "client_name": "ACME GmbH",
                    "site_name": "Hauptsitz",
                    "status": "online",
                    "plat": "windows",
                    "public_ip": "203.0.113.9",
                    "local_ips": "10.0.0.5, 10.0.0.6"
                },
                {
                    "agent_id": "def456",
                    "hostname": "WS-07",
                    "client_name": "Contoso AG",
                    "site_name": "Zweigstelle",
                    "status": "offline",
                    "plat": "linux",
                    "public_ip": null,
                    "local_ips": "error getting local ips"
                }
            ]"#,
        )
        .unwrap();

        let agents = map_agents_response(&json).unwrap();

        assert_eq!(agents.len(), 2);
        assert_eq!(agents[0].external_id, "abc123");
        assert_eq!(agents[0].name, "SRV-01");
        assert_eq!(agents[0].client_name, "ACME GmbH");
        assert_eq!(agents[0].site_name.as_deref(), Some("Hauptsitz"));
        assert_eq!(agents[0].status.as_deref(), Some("online"));
        assert_eq!(agents[0].platform.as_deref(), Some("windows"));
        assert_eq!(agents[0].ip_address.as_deref(), Some("10.0.0.5"));
        assert_eq!(agents[1].external_id, "def456");
        assert_eq!(agents[1].client_name, "Contoso AG");
        // local_ips is the literal Tactical RMM error string -> falls back
        // to public_ip, which is itself null here -> None.
        assert_eq!(agents[1].ip_address, None);
    }

    #[test]
    fn agents_rejects_non_array_json() {
        let json = serde_json::json!({"not": "an array"});
        let result = map_agents_response(&json);
        assert!(matches!(result, Err(PluginError::UnexpectedResponse(_))));
    }

    #[test]
    fn agent_skips_entries_without_agent_id() {
        let json = serde_json::json!([{"hostname": "OhneId", "client_name": "ACME"}]);
        let agents = map_agents_response(&json).unwrap();
        assert!(agents.is_empty());
    }

    #[test]
    fn agent_skips_entries_without_client_name() {
        let json = serde_json::json!([{"agent_id": "abc", "hostname": "OhneClient"}]);
        let agents = map_agents_response(&json).unwrap();
        assert!(agents.is_empty());
    }

    #[test]
    fn agent_falls_back_to_agent_id_when_no_hostname_present() {
        let json = serde_json::json!([{"agent_id": "abc", "client_name": "ACME"}]);
        let agents = map_agents_response(&json).unwrap();
        assert_eq!(agents[0].name, "abc");
        assert_eq!(agents[0].hostname, None);
    }

    #[test]
    fn extract_ip_address_prefers_first_local_ip() {
        let value =
            serde_json::json!({"local_ips": "10.0.0.5, 10.0.0.6", "public_ip": "203.0.113.9"});
        assert_eq!(extract_ip_address(&value).as_deref(), Some("10.0.0.5"));
    }

    #[test]
    fn extract_ip_address_falls_back_to_public_ip_when_local_ips_is_error_string() {
        let value =
            serde_json::json!({"local_ips": "error getting local ips", "public_ip": "203.0.113.9"});
        assert_eq!(extract_ip_address(&value).as_deref(), Some("203.0.113.9"));
    }

    #[test]
    fn extract_ip_address_falls_back_to_public_ip_when_local_ips_missing() {
        let value = serde_json::json!({"public_ip": "203.0.113.9"});
        assert_eq!(extract_ip_address(&value).as_deref(), Some("203.0.113.9"));
    }

    #[test]
    fn extract_ip_address_is_none_when_neither_field_usable() {
        let value = serde_json::json!({"local_ips": "error getting local ips"});
        assert_eq!(extract_ip_address(&value), None);
    }

    #[test]
    fn maps_401_status_to_authentication_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(401));
        assert!(matches!(err, PluginError::Authentication(_)));
    }

    #[test]
    fn maps_403_status_to_authentication_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(403));
        assert!(matches!(err, PluginError::Authentication(_)));
    }

    #[test]
    fn maps_other_status_codes_to_unreachable_error() {
        let err = map_ureq_error(ureq::Error::StatusCode(500));
        assert!(matches!(err, PluginError::Unreachable(_)));
    }

    #[test]
    fn plugin_id_returns_configured_connection_id() {
        let plugin = TacticalRmmPlugin::new(
            "tacticalrmm:acme-123".to_string(),
            "https://api.rmm.example.com".to_string(),
        );
        assert_eq!(plugin.id(), "tacticalrmm:acme-123");
    }
}
